### ISSUE TITLE
Basic auth not working

### ISSUE THREAD

**Issue by matt-shaw** [spotify/dockerfile-maven#100]
Hi,

I'm using dockerfile-maven-plugin 1.3.6, maven 3.5.0, java 8, docker 17.10.0-ce

When I try to deploy an image to our local Nexus 3 I get the error: no basic auth credentials

My pom is;

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	
	<parent>
		<groupId>reference.boot</groupId>
		<artifactId>boot</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>

	
	<artifactId>discovery-app</artifactId>
	<packaging>jar</packaging>
	<name>Reference Service Discovery</name>
	<description>Reference Service Discovery</description>
	
	<properties>
		<systemName>reference</systemName>
		<dockerRepo>aow-repo:10003</dockerRepo>
		<mainClass>com.reference.boot.discovery.DiscoveryApplication</mainClass>
	</properties>
	
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka-server</artifactId>
		</dependency>
	</dependencies>

	<build>
		<finalName>discovery-app</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>1.5.8.RELEASE</version>
				<configuration>
					<addResources>true</addResources>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
				
	
	<profiles>
		<profile>
			<id>docker</id>
			<activation>
				<activeByDefault>false</activeByDefault>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>com.spotify</groupId>
						<artifactId>dockerfile-maven-plugin</artifactId>
						<version>1.3.6</version>
						<executions>
							<execution>
								<id>default</id>
								<goals>
									<goal>build</goal>
									<goal>push</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<repository>${dockerRepo}/${systemName}/${project.build.finalName}</repository>
							<tag>${project.version}</tag>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>

My C:\Users\<username>\.docker\config.json is;

{
	"auths": {
XXX
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/17.10.0-ce (windows)"
	}
}

There seems to have been lots of discussions and issues raised around this area but I'm not sure of the current working state of this feature?

Matt

**Comment by 56quarters** [comment]
Just FYI @matt-shaw, the credentials in `config.json` are just base64 encoded so you probably need to change them now ☹️

**Comment by uvwild** [comment]
I can see from debugging the code that the repository server gets extracted the wrong way.
with a local image registry URL it looks for **docker.io** credentials in the **useMavenSettingsForAuth** mode.

**Comment by yangcheng2503** [comment]
[https://github.com/spotify/docker-client/issues/804](url)
I don´t really know if this is a bug in docker-client.

**Comment by McKratt** [comment]
Any news on this issue ? It is the last thing missing to finally use this plugin.

**Comment by McKratt** [comment]
Ok, I finally updated the version of the plugin and this issue seems resolved.
Plugin versio  tested : 1.4.3.

**Comment by jl2035** [comment]
Any ideas for me? I'm getting this error with every version I try. :(

**Comment by Shrewd** [comment]
> I can see from debugging the code that the repository server gets extracted the wrong way.
> with a local image registry URL it looks for **docker.io** credentials in the **useMavenSettingsForAuth** mode.
> 
> There is a bug when providing the image name.
> Its not working for local repositories since someone though using a dot in the hostname is a sufficient indication for this:
> com/spotify/docker/client/ImageRef.class
> private static boolean isRegistry(String part) {
> return part.contains(".");
> }
> 
> So obviously it cannot work for local not internet connected docker-registry without a domainname.
> Bummer.

I think this is still a bug in 1.4.13 since I was having troubles pushing to my own nexus repository using "localhost"
I had to change hosts file for it to work.
Adding : 
`"127.0.0.1		localhost.com"`
Doing this and changing the pom file to use localhost.com as repository did the trick
