### ISSUE TITLE
Maven authentication does not retrieve encrypted password

### ISSUE THREAD

**Issue by MarcoLotz** [spotify/dockerfile-maven#107]
I am currently experiencing problems when encrypting the password in maven. Authentication is only working when I use the non-encrypted version.

Comparing with the docker-client equivalent [part:](https://github.com/spotify/docker-maven-plugin/blob/af37f371fd4c0fc2cabc5e751a65ae39bbe0c325/src/main/java/com/spotify/docker/AbstractDockerMojo.java) line 247

And here is like [this](https://github.com/rlodge/dockerfile-maven/blob/e4b9b79233e6ee80ac2a4f015928aae696d4ac6d/plugin/src/main/java/com/spotify/plugin/dockerfile/MavenRegistryAuthSupplier.java) line 52

Looks like here is missing the decryption part. Would that be the case @mattnworb?
If yes, I can fix it later today.

**Comment by johanrydstrom** [comment]
Started working on it.

**Comment by aranjitchi** [comment]
hi,

i have same issue. i found and tested this patch on the following id [#78](https://github.com/spotify/dockerfile-maven/issues/78) . 

@johanrydstrom, it is possible to integrate the patch on the next SNAPSHOT version?
