### ISSUE TITLE
Feature request - Support for symlinks

### ISSUE THREAD

**Issue by pbillen** [spotify/dockerfile-maven#108]
Hi,

I would like to propose a feature request. My project structure looks as following:

```
/module-a
    pom.xml
    Dockerfile
/module-...
    ...
/scripts
    /postgres
    /rabbitmq
    /redis
    /elasticsearch
    /...
pom.xml
```

In `module-a`, I am using `spotify/dockerfile-maven` to build a Docker image. I would like to include resources from `/scripts`, so I can copy them to the docker image. More concrete, it would be useful if I could create a symlink from `module-a/postgres` to `../scripts/postgres` (for example) and add `COPY postgres /` to the `Dockerfile`.

I know this is by default not supported by Docker, for various reasons. But still, it would  be useful if this could be supported by `spotify/dockerfile-maven`. There is an approach to achieve this quite easily. You could build the image as following:

`tar -czh . | docker build -t <image:tag> -` (instead of `docker build -t <image:tag> .`)

This resolves all links, packages the working directory and then pipes this directory to the Docker build target. In the `Dockerfile`, you can then do `COPY postgres /`.

What do you think?

Thank you!

**Comment by mattnworb** [comment]
Thanks for the suggestion. I would be wary of adding something that isn’t supported by Docker or that would mean that a docker build from the command-line on the same Dockerfile and context directory wouldn’t function.

**Comment by pbillen** [comment]
Closing: as an afterthought, I agree with @mattnworb!
