### ISSUE TITLE
"Multi auth" logic is overzealous

### ISSUE THREAD

**Issue by paul-hammant** [spotify/dockerfile-maven#114]
I've set -Ddockerfile.username and -Ddockerfile.password yet they are being ignored because `AbstractDockerMojo.createRegistryAuthSupplier()` adds everything it can in a multi-auth.

If username and password are set on the command line (or in the POM itself), then there is no need to recursively try other auth mechanisms.  The logic should be: 

```
    MavenPomAuthSupplier pomSupplier = new MavenPomAuthSupplier(this.username, this.password);
    if (pomSupplier.hasUserName()) {
      suppliers.add(pomSupplier);
    } else {
      if (useMavenSettingsForAuth) {
        suppliers.add(new MavenRegistryAuthSupplier(session.getSettings()));
      }

      if (dockerConfigFile == null || "".equals(dockerConfigFile.getName())) {
        suppliers.add(new ConfigFileRegistryAuthSupplier());
      } else {
        suppliers.add(
                new ConfigFileRegistryAuthSupplier(
                        new DockerConfigReader(),
                        dockerConfigFile.toPath()
                )
        );
      }

      if (googleContainerRegistryEnabled) {
        try {
          final RegistryAuthSupplier googleSupplier = googleContainerRegistryAuthSupplier();
          if (googleSupplier != null) {
            suppliers.add(0, googleSupplier);
          }
        } catch (IOException ex) {
          getLog().info("Ignoring exception while loading Google credentials", ex);
        }
      } else {
        getLog().info("Google Container Registry support is disabled");
      }
    }
```

Specifically, they should be reordered, and else conditions inserted into the logic.

My proximate cause was that my `~/.docker/config.json` doesn't contain a username and password, yet this plugin finds the file and effectively operationalizes it and ignores the username/password that I am setting explicitly via the -D properties for mvn.  I had to set breakpoints in the plugin to determine this because it is silent.

Also, it would be great if the plugin INFO communicated which auth provider it has selected. I keep seeing my GCP ID spat out in builds and I'm wondering why when I had no intention of using those credentials for Docker, and and 1000000000% sure I don't want the shoved up to DockerHub in an attempt to log me in. Of course I don't know if it is or not, just get a mini heart-attack when I see the GCP id in the build log.

**Comment by mattnworb** [comment]
I think it should be enough for the MavenPomAuthSupplier to be the first in the list, since the list of suppliers is checked in order. I agree it makes sense that if you specify `-Ddockerfile.username=...` to use that AuthSupplier first.

Would you like to make a PR with the code change? I think that is the easiest and fastest way to get changes like what you propose merged.

**Comment by paul-hammant** [comment]
I'll do the PR, sure. I've one in already for #112 and I'll watch that one in advance of doing this one :)

**Comment by srenkens** [comment]
Also experiencing this issue. My `~/.docker/config.json` gets picked up, but it cannot provide the credentials for the registry I am trying to authenticate to. These credentials are provides through the environment `-Ddockerfile.username and -Ddockerfile.password` but these are skipped....
