### ISSUE TITLE
Make dockerfile location configurable

### ISSUE THREAD

**Issue by sta-szek** [spotify/dockerfile-maven#117]
I have project structure like this:
target/app.jar
src/docker/Dockerfile

I want to specify where the dockerfile is but do not change contextDirectory.

My proposal is to provide additional variable e.g.:
```
@Parameter(defaultValue = "${project.basedir}/Dockerfile",
      property = "dockerfile.dockerfile-location",
      required = true)
  private File dockerfile;
```

Also change condition in https://github.com/spotify/dockerfile-maven/blob/master/plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java#L144:
from `if (!new File(contextDirectory, "Dockerfile").exists() && !new File(contextDirectory, "dockerfile").exists())` to `if (!new File(contextDirectory, "Dockerfile").exists())` as official naming convention is to use `Dockerfile` filename.

And when it will be configurable someone can change this to `dockerfile`

**Comment by deripas** [comment]
+1 
I want have separate paths for Dockerfile and for target directory.
In **docker-maven-plugin** my config:
```xml
<plugin>
                    <groupId>com.spotify</groupId>
                    <artifactId>docker-maven-plugin</artifactId>
                    <version>1.0.0</version>
                    <configuration>
                        <image>${project.artifactId}</image>
                        <imageName>${docker.registry}/${project.artifactId}</imageName>
                        <dockerDirectory>${project.basedir}/src/main/docker</dockerDirectory>
                        <resources>
                            <resource>
                                <targetPath>/</targetPath>
                                <directory>${project.build.directory}</directory>
                                <include>${project.build.finalName}.jar</include>
                            </resource>
                        </resources>
                    </configuration>
                </plugin>
```

How I can migrate to dockerfile-maven plugin?
Thank you!

**Comment by NicoTexas** [comment]
Much needed enhancement. Seems like there is already an opened pull request for this.
https://github.com/spotify/dockerfile-maven/pull/89

**Comment by jl2035** [comment]
Why is this closed? Was the PR ever merged?

**Comment by MTKnife** [comment]
#89 supposedly added this functionality in 1.4.10, but I can't get it to work for a dockerfile located somewhere other than the context root directory.
