### ISSUE TITLE
Plugin does not read docker config

### ISSUE THREAD

**Issue by jtdudley2** [spotify/dockerfile-maven#12]
Plugin does not read credentials from ~/.docker/config.json or ~/.dockercfg

**Comment by awallat** [comment]
It's the same under Windows 10. I cannot build an image where the parent image is from a secure private repository.

**Comment by mattnworb** [comment]
v1.3.0 of the plugin adds support for reading the authentication info from your ~/.dockercfg or ~/.docker/config.json file, see the README for more.

**Comment by declension** [comment]
@awallat I had this too, but the problem (for me) was more subtle, due to the (default?) usage of externalised credentials store on Docker on Windows 10, so see #24...
