### ISSUE TITLE
Copy file from host 

### ISSUE THREAD

**Issue by nissane** [spotify/dockerfile-maven#120]
Am I not able to copy files from my host machine onto my docker image?

in my dockerfile I have:
ADD /data/myfile.txt myfile.txt

but I get 
[ERROR] ADD failed: stat /data/docker/tmp/docker-builder401511410/data/myfile.txt: no such file or directory

Thanks!

**Comment by mattnworb** [comment]
`ADD` is relative to the docker context, does `/data/myfile.txt` exist inside the context you are sending to docker?

> ADD obeys the following rules:
>
> - The <src> path must be inside the context of the build; you cannot ADD ../something /something, because the first step of a docker build is to send the context directory (and subdirectories) to the docker daemon.

https://docs.docker.com/engine/reference/builder/#add

**Comment by nissane** [comment]
Thanks.  I am running this on a jenkins server.  so /data/myfile.txt resides in my jenkins server.  would I only be able to copy from inside my jenkins build directory then?
