### ISSUE TITLE
How can I use the plugin for deploy a .war application in wildfly?

### ISSUE THREAD

**Issue by han057** [spotify/dockerfile-maven#125]
Is it posible to use the plugin to deploy a .war application in a wildfly container?
I have this Dockerfile

FROM jboss/wildfly
ADD myapp.war /opt/jboss/wildfly/standalone/deployments/

Error message:

ADD failed: stat /var/lib/docker/tmp/docker-builder686836659/myapp.war: no such file or directory
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.311 s
[INFO] Finished at: 2018-01-08T23:47:22+01:00
[INFO] Final Memory: 43M/388M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.6:build (default) on project myapp: Could not build image: ADD failed: stat /var/lib/docker/tmp/docker-builder686836659/myapp.war: no such file or directory -> [Help 1]

What is the configuration to correctly copy myapp.war?

I know is not an issue but I don't know where I can ask.

thanks.

**Comment by mattnworb** [comment]
It is hard to know without seeing your pom but I would guess the problem here is that your Docker context is the basedir of your project, but the war file is being produced as `target/myapp.war`.

**Comment by han057** [comment]
Hello, 

As you said I changed to target/myapp.war and changed the JAR_FILE variable to WAR_FILE in pom and now everything is ok.
pom.xml
...
<plugin>
	<groupId>com.spotify</groupId>
	<artifactId>dockerfile-maven-plugin</artifactId>
	<version>1.3.6</version>
	<executions>
		<execution>
			<id>default</id>
			<goals>
				<goal>build</goal>
				<goal>push</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<repository>myapp</repository>
		<tag>${project.version}</tag>
		<buildArgs>
			<WAR_FILE>${project.build.finalName}.war</WAR_FILE>
		</buildArgs>
	</configuration>
</plugin>
...

Dockerfile
...
FROM jboss/wildfly
ARG WAR_FILE
ADD target/${WAR_FILE} /opt/jboss/wildfly/standalone/deployments/
...

Thanks!
