### ISSUE TITLE
MuLtiple module projects

### ISSUE THREAD

**Issue by bowen-yangxiansen** [spotify/dockerfile-maven#127]
my project structure is like this:
```
parent:
     pom.xml
     child_1:
          pom.xml
          Dockerfile
     child_2:
          pom.xml
          Dockerfile
```
but i just want to build a sub-project one

**Comment by bowen-yangxiansen** [comment]
already solved,thanks

**Comment by caipre** [comment]
In case folks find this, we have an example here: https://github.com/spotify/dockerfile-maven/tree/master/plugin/src/it/advanced
