### ISSUE TITLE
Error: Invalid or corrupt jarfile /app.jar

### ISSUE THREAD

**Issue by DILEEP-YADAV** [spotify/dockerfile-maven#133]
`docker run -p 8080:8080 -t 770727c11311`
`Error: Invalid or corrupt jarfile /app.jar`

I am using the following sample  app to make my own docker image 
https://github.com/spring-guides/gs-spring-boot-docker.git

docker image builds successfully. and working fine with my laptop with docker terminal for windows 10.
but the same image pushed to gitlab docker registry. and using my VPS Centos server. it is getting the same error. Please help me. Or even pulling to same docker image to docker terminal for windows 10. getting the same error. 

![error](https://user-images.githubusercontent.com/8583769/35532288-bf74a168-055f-11e8-9005-093de47c0599.PNG)

**Comment by DILEEP-YADAV** [comment]
Dockerfile


FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
ADD ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

**Comment by DILEEP-YADAV** [comment]
pom.xml 

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.go</groupId>
	<artifactId>go</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>go</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.9.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<docker.image.prefix>goapp</docker.image.prefix>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>dockerfile-maven-plugin</artifactId>
				<version>1.3.6</version>
				<configuration>
					<repository>${docker.image.prefix}/${project.artifactId}</repository>
					<buildArgs>
						<JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
					</buildArgs>
				</configuration>
			</plugin>
			

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>unpack</id>
						<phase>package</phase>
						<goals>
							<goal>unpack</goal>
						</goals>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>${project.groupId}</groupId>
									<artifactId>${project.artifactId}</artifactId>
									<version>${project.version}</version>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>


</project>

**Comment by imne** [comment]
Hi Dileep

In your docker file change the java version from "openjdk:8-jdk-alpine" to "java:8" that should resolve your issue

**Comment by fsdcyr** [comment]
maybe you should move maven-dependency-plugin to the first order,and spring-boot-maven-plugin the second, dockerfile-maven-plugin the last.

**Comment by abhinavmall** [comment]
Changing openjdk to java:8 does not work.
Still getting "Error: Invalid or corrupt jarfile /app.jar"

The jar runs fine otherwise.

**Comment by abhinavmall** [comment]
Workaround - 

FROM java:8
VOLUME /tmp
ADD target/<jarname>.jar app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

Then use docker build.

This method is not a good fix in my opinion, but it will make the app run on docker container. Further working on integrating with docker-maven-plugin.
Will update this thread then.

**Comment by msharma84** [comment]
This worked for me - 
Docker file content

FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD <target jar file name> app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","app.jar"]


I want my image to build with this name - 'spring-boot-docker'
So for this i am using the docker command 

docker run -p 8080:8080 -t spring-boot-docker

Image has been build and checked on the browser with localhost:8080
