### ISSUE TITLE
buildArgs encoding is converting spaces to +

### ISSUE THREAD

**Issue by ncouse** [spotify/dockerfile-maven#136]
If I have spaces in my build arguments, they get converted to + symbols.

For example if I can add configuration like this:
```
<configuration>
	<buildArgs>
		<SOME_ARG>hello world</SOME_ARG>
	</buildArgs>
</configuration>
```

When I actually use that argument in a Dockerfile is will look like
```
hello+world
```

**Comment by ncouse** [comment]
The problem seems to be in the `BuilderMojo` code:

```
        final String encodedBuildArgs = URLEncoder.encode(new Gson().toJson(buildArgs), "utf-8");
        buildParameters.add(new DockerClient.BuildParam("buildargs", encodedBuildArgs));
```

The JSON conversion works properly, and it gets converted to `{"SOME_ARG":"hello world"}`
However the URL Encoding of this is where the problem would appear to lie, and it gets converted to `%7B%22SOME_ARG%22%3A%22hello+world%22%7D`

Note that spaces in build arguments is supported by Docker, and I have several use cases where we would need spaces in arguments.

**Comment by delfuego** [comment]
I too am hitting this; my entire build server directory structure has spaces in the project directory names.

Any chance of this being fixed?

**Comment by ncouse** [comment]
Bumping this to stop the stale bot. This issue is problematic. Have worked around it for now, but prevents me using it properly.

**Comment by ncouse** [comment]
Bump.

**Comment by jrmcdonald** [comment]
I am also running into this issue when using build args to set descriptive labels in containers.

@ncouse Out of curiosity, how did you work around this?

**Comment by thibgc** [comment]
We are having the same issue, but this issue has been closed by the stale bot.

**Comment by thibgc** [comment]
@ncouse @jrmcdonald This issue is closed so new comments probably won't go anywhere. I've re-opened a brand new issue, #286 -- please go there and comment.
