### ISSUE TITLE
[feature-request] Remove intermediate containers after build

### ISSUE THREAD

**Issue by dminca** [spotify/dockerfile-maven#144]
## Preamble
After using this plugin on our buildmachines, we noticed after a period of time that our agents were failing to execute pipelines because disk was filling quite fast. The builds were not being able to cleanup after themselves with the help of this plugin because it didn't have this feature.

## Request details
During the `docker build` phase, we're requiring a mechanism to remove intermediate containers after a successful build. This option comes native in the `docker-engine`: `docker build --rm <other-params>`

As I saw by [browsing through the issues](https://github.com/spotify/dockerfile-maven/issues/4), the `docker build --no-cache` option already exists (which is awesome), imagine if you combine it with the `--rm` argument, then no one would actually be forced to setup cleanup crons on buildmachines for cleaning up containers/images.

```sh
# docker-build manpage: man docker-build
--rm=true|false
   Remove intermediate containers after a successful build. The default is true.
```

Please consider implementing this feature, as I don't think I'm the only one wanting to evade from these kind of errors, you're going to help many SysAdmins and Developers :sweat_smile: 

![screenshot from 2018-02-19 17-55-36](https://user-images.githubusercontent.com/5355219/36386482-8fd534d2-159e-11e8-8b3e-ba94a51a9efb.png)

**Comment by GhaTMA** [comment]
hi @dminca,
did you try doing this:
`
<plugin>
  <groupId>com.spotify</groupId>
  <artifactId>docker-maven-plugin</artifactId>
    <configuration>
      <rm>true</rm>
       ...
    </configuration>
    ....
</plugin>
`
Just found it in the xml definition of the plugin (version 1.4.0)

**Comment by melozo** [comment]
Adding both features would be interesting, but I think they go beyond the scope of not having space or saving disk space. You have options to perform cleaning on your system, as they can be:

```sh
$ docker system prune
$ docker image prune
```

**Comment by testphreak** [comment]
Not sure why the issue remains unresolved after 5 months. If it's due to time constraints I understand. 

That said, to keep build environments as clean as possible and for it to be done within the Maven context I added the following workaround to remove intermediate containers.

```xml
<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>exec-maven-plugin</artifactId>
	<version>1.6.0</version>
	<executions>
		<execution>
			<id>prune-images</id>
			<phase>package</phase>
			<configuration>
				<executable>docker</executable>
				<arguments>
					<argument>system</argument>
					<argument>prune</argument>
					<argument>-f</argument>
				</arguments>
			</configuration>
			<goals>
				<goal>exec</goal>
			</goals>
	         </execution>
	</executions>
</plugin>
```

Would have been nice for the plugin to prune after itself, but since that isn't there, this seems like the next best alternative.

**Comment by lassounski** [comment]
> Not sure why the issue remains unresolved after 5 months. If it's due to time constraints I understand.
> 
> That said, to keep build environments as clean as possible and for it to be done within the Maven context I added the following workaround to remove intermediate containers.
> 
> ```
> <plugin>
> 	<groupId>org.codehaus.mojo</groupId>
> 	<artifactId>exec-maven-plugin</artifactId>
> 	<version>1.6.0</version>
> 	<executions>
> 		<execution>
> 			<id>prune-images</id>
> 			<phase>package</phase>
> 			<configuration>
> 				<executable>docker</executable>
> 				<arguments>
> 					<argument>system</argument>
> 					<argument>prune</argument>
> 					<argument>-f</argument>
> 				</arguments>
> 			</configuration>
> 			<goals>
> 				<goal>exec</goal>
> 			</goals>
> 	         </execution>
> 	</executions>
> </plugin>
> ```
> 
> Would have been nice for the plugin to prune after itself, but since that isn't there, this seems like the next best alternative.

Works like a charm, thanks!
