### ISSUE TITLE
Previous image not getting replaced. 

### ISSUE THREAD

**Issue by RohitBarnwal** [spotify/dockerfile-maven#145]
Whenever I run "mvn clean verify" it creates a new docker image with mentioned repo name and tag, however if I run "mvn clean verify" again then already created docker image doesn't get removed. Rather it goes into none state. 

REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
rohitbarnwal7/presto        0.0.1                  fdc132dfeg453        About an hour ago   1.54GB
<none>                             <none>              bfd0e21b86cd        About an hour ago   1.54GB

Any help would be highly appreciated.

**Comment by mattnworb** [comment]
This is the same as how “docker build” works. To remove the previous image you have to explicitly remove it.

**Comment by JeanPascalR** [comment]
Hi,
This is not how docker build works.
If I run `docker build -t foo/bar:1.0 .` twice, the second image built will replace the first one. This is not how the plugin works.
