### ISSUE TITLE
Latest release 1.4.0 not on Maven Central?

### ISSUE THREAD

**Issue by mnoky** [spotify/dockerfile-maven#149]
Hi, I saw there was a 1.4.0 release on Feb 8. However, that release has not made it's way to Maven Central yet. Is there some sort of mechanism which is supposed to deploy releases there? I was looking forward to using this in a project, since it looks like the docker-client dependency has been updated. Thanks so much, really love this plugin!

**Comment by mattnworb** [comment]
@davidxia do you know what happened here? I see a commit in https://github.com/spotify/dockerfile-maven/commits/master bumping the version but not one for the release of v1.4.0.

**Comment by davidxia** [comment]
Sorry, no idea what happened with that missing commit. I'm re-releasing 1.4.0 now.

**Comment by davidxia** [comment]
Ah I used the wrong `mvn` command last time. I should've used `mvn -P release -Dgpg.keyname=$KEY_ID release:prepare release:perform`. Now the right commits [are there](https://github.com/spotify/dockerfile-maven/commits/master). 1.4.0 should be on maven central soon. http://search.maven.org/#search|ga|1|dockerfile-maven Let me know if it doesn't appear.
