### ISSUE TITLE
Missing Dockerfile in context directory for maven parent

### ISSUE THREAD

**Issue by IrimieBogdan** [spotify/dockerfile-maven#153]
```
parent:
pom.xml
    child1:
        Dockerfile
       pom.xml
        <src>
    child2:
        Dockerfile
        pom.xml
        <src>
```
When running `mvn dockerfile:build dockerfile:push` from each child, everything works as expected, but when running the same command from the parent, the fallowing error appears `Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.6:build (default-cli) on project ...: Missing Dockerfile in context directory: parent`

Is there a way to tell the plugin to skip maven parents as they should not be packaged in a docker container?

**Comment by mattnworb** [comment]
there are a few different approaches mentioned in #87 that might help. If you are configuring the plugin globally in the parent pom.xml then you might want to add configuration to have it skipped in the parent (i.e. not in the `<pluginManagement>` section)
