### ISSUE TITLE
Authenticating with maven pom.xml

### ISSUE THREAD

**Issue by oawang** [spotify/dockerfile-maven#155]
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.0:build (default-cli) on project sibu-shop-order-service: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: co
m.spotify.docker.client.shaded.org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect -> [Help 1]
[ERROR]

**Comment by oawang** [comment]
<plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default</id>
                        <goals>
                            <goal>build</goal>
                            <goal>push</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <username>myuser</username>
                    <password>mypwd123@!</password>
                    <repository>${docker.repository}</repository>
                    <tag>${project.version}</tag>
                    <buildArgs>
                        <JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
                        <JAVA_OPTS>${JAVA_OPTS}</JAVA_OPTS>
                    </buildArgs>
                </configuration>
            </plugin>

**Comment by oawang** [comment]
`<plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default</id>
                        <goals>
                            <goal>build</goal>
                            <goal>push</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <username>myuser</username>
                    <password>mypwd123@!</password>
                    <repository>${docker.repository}</repository>
                    <tag>${project.version}</tag>
                    <buildArgs>
                        <JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
                        <JAVA_OPTS>${JAVA_OPTS}</JAVA_OPTS>
                    </buildArgs>
                </configuration>
            </plugin>`

**Comment by AntonyBaasan** [comment]
I think this will be same issue as this one:
https://github.com/spotify/dockerfile-maven/issues/55
