### ISSUE TITLE
Cannot build image without internet access

### ISSUE THREAD

**Issue by oschlueter** [spotify/dockerfile-maven#160]
Hello,

I've configured dockerfile-maven:1.4.0 via my POM and everything is working fine until I'm trying to work offline. In order to build the project and the image I use `mvn package` and receive the following output:

[docker-offline.txt](https://github.com/spotify/dockerfile-maven/files/1819649/docker-offline.txt)

Is there a way I can build my images without internet connection? 

Also, is there a way I can have the newly created image automagically tagged as `latest`?

**Comment by mattnworb** [comment]
You can set `pullNewerImage` to false in the plugin configuration, but note that that will only be useful if the image trying to be pulled already exists in your local docker cache.

https://github.com/spotify/dockerfile-maven/blob/49782a201fae60d05f49897280770e73202cd59a/plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java#L77-L81
