### ISSUE TITLE
dockerfile-maven not recognized as deployment plugin

### ISSUE THREAD

**Issue by tormodatt** [spotify/dockerfile-maven#162]
```
mvn deploy
> Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter
```

Which is correct, but I shouldn't need one, since the only thing I want to deploy to, is the remote docker register.

If I set up a `distributionManagement` to a local file, it works as fine. Is this the expected behavior? And if so, are there some other workaround than deploying to file?

in ./pom.xml I have
```
    <extensions>
      <extension>
        <groupId>com.spotify</groupId>
        <artifactId>dockerfile-maven-extension</artifactId>
        <version>1.4.0</version>
      </extension>
    </extensions>
````
while in ./submodule/pom.xml, I have:
```
      <plugin>
        <groupId>com.spotify</groupId>
        <artifactId>dockerfile-maven-plugin</artifactId>
        <version>1.4.0</version>
        <executions>
          <execution>
            <id>build-image</id>
            <phase>package</phase>
            <goals>
              <goal>build</goal>
            </goals>
            <configuration>
                <repository>my-repo</repository>
                <tag>latest</tag>
                <buildArgs>
                  <JAR_FILE>${project.build.finalName}.jar</JAR_FILE>
                </buildArgs>
            </configuration>
          </execution>
          <execution>
            <id>push-image</id>
            <phase>deploy</phase>
            <goals>
              <goal>tag</goal>
              <goal>push</goal>
            </goals>
            <configuration>
                <tag>${project.version}</tag>
                <repository>my-host.com/my-repo</repository>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by tormodatt** [comment]
for now I'm using, `mvn package`, `mvn -f submodule dockerfile:push`, with the tag goal moved to its own execution.

**Comment by HADB** [comment]
same problem

**Comment by lucianbc** [comment]
I found a solution. You should skip pushing your package to an artifact manager and you can do this by adding this plugin to your pom.xml.

`
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
`
More details here: https://aerben.me/2017/docker-maven-1/

**Comment by yizhixiaotaozi** [comment]
same problem

**Comment by mattnworb** [comment]
@lucianbc's solution above is correct. When you run `mvn deploy`, Maven runs all plugins attached to the `deploy` phase - including the built in `org.apache.maven.plugins:maven-deploy-plugin`.

**Comment by jvleminc** [comment]
FYI, @lucianbc's solution worked for me; what @mattnworb suggested did not.
