### ISSUE TITLE
Execution default-cli of goal com.spotify:dockerfile-maven-plugin:1.3.6:build failed: A required class was missing while executing com.spotify:dockerfile-maven-plugin:1.3.6:build: org/apache/commons/logging/LogFactory

### ISSUE THREAD

**Issue by zhangshexin** [spotify/dockerfile-maven#170]
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.6:build (default-cli) on project eurekaserver: Execution default-cli of goal com.spotify:dockerfile-maven-plugin:1.3.6:build failed: A required class was missing while executing com.spotify:dockerfile-maven-plugin:1.3.6:build: org/apache/commons/logging/LogFactory
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.spotify:dockerfile-maven-plugin:1.3.6
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/qbq_wzk/.m2/repository/com/spotify/dockerfile-maven-plugin/1.3.6/dockerfile-maven-plugin-1.3.6.jar
[ERROR] urls[1] = file:/Users/qbq_wzk/.m2/repository/com/spotify/docker-client/8.8.1/docker-client-8.8.1-shaded.jar
[ERROR] urls[2] = file:/Users/qbq_wzk/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.8.8/jackson-jaxrs-json-provider-2.8.8.jar
[ERROR] urls[3] = file:/Users/qbq_wzk/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.8.8/jackson-jaxrs-base-2.8.8.jar
[ERROR] urls[4] = file:/Users/qbq_wzk/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.8/jackson-core-2.8.8.jar
[ERROR] urls[5] = file:/Users/qbq_wzk/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.8.8/jackson-module-jaxb-annotations-2.8.8.jar
[ERROR] urls[6] = file:/Users/qbq_wzk/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-guava/2.8.8/jackson-datatype-guava-2.8.8.jar
[ERROR] urls[7] = file:/Users/qbq_wzk/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.8/jackson-databind-2.8.8.jar
[ERROR] urls[8] = file:/Users/qbq_wzk/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar
[ERROR] urls[9] = file:/Users/qbq_wzk/.m2/repository/org/glassfish/jersey/core/jersey-client/2.22.2/jersey-client-2.22.2.jar
[ERROR] urls[10] = file:/Users/qbq_wzk/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar
[ERROR] urls[11] = file:/Users/qbq_wzk/.m2/repository/org/glassfish/jersey/core/jersey-common/2.22.2/jersey-common-2.22.2.jar
[ERROR] urls[12] = file:/Users/qbq_wzk/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
[ERROR] urls[13] = file:/Users/qbq_wzk/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.jar
[ERROR] urls[14] = file:/Users/qbq_wzk/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar
[ERROR] urls[15] = file:/Users/qbq_wzk/.m2/repository/org/glassfish/hk2/hk2-api/2.4.0-b34/hk2-api-2.4.0-b34.jar
[ERROR] urls[16] = file:/Users/qbq_wzk/.m2/repository/org/glassfish/hk2/hk2-utils/2.4.0-b34/hk2-utils-2.4.0-b34.jar
[ERROR] urls[17] = file:/Users/qbq_wzk/.m2/repository/org/glassfish/hk2/external/aopalliance-repackaged/2.4.0-b34/aopalliance-repackaged-2.4.0-b34.jar
[ERROR] urls[18] = file:/Users/qbq_wzk/.m2/repository/org/glassfish/hk2/external/javax.inject/2.4.0-b34/javax.inject-2.4.0-b34.jar
[ERROR] urls[19] = file:/Users/qbq_wzk/.m2/repository/org/glassfish/hk2/hk2-locator/2.4.0-b34/hk2-locator-2.4.0-b34.jar
[ERROR] urls[20] = file:/Users/qbq_wzk/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar
[ERROR] urls[21] = file:/Users/qbq_wzk/.m2/repository/org/glassfish/jersey/connectors/jersey-apache-connector/2.22.2/jersey-apache-connector-2.22.2.jar
[ERROR] urls[22] = file:/Users/qbq_wzk/.m2/repository/org/glassfish/jersey/media/jersey-media-json-jackson/2.22.2/jersey-media-json-jackson-2.22.2.jar
[ERROR] urls[23] = file:/Users/qbq_wzk/.m2/repository/org/glassfish/jersey/ext/jersey-entity-filtering/2.22.2/jersey-entity-filtering-2.22.2.jar
[ERROR] urls[24] = file:/Users/qbq_wzk/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar
[ERROR] urls[25] = file:/Users/qbq_wzk/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
[ERROR] urls[26] = file:/Users/qbq_wzk/.m2/repository/org/apache/httpcomponents/httpclient/4.5/httpclient-4.5.jar
[ERROR] urls[27] = file:/Users/qbq_wzk/.m2/repository/org/apache/httpcomponents/httpcore/4.4.5/httpcore-4.4.5.jar
[ERROR] urls[28] = file:/Users/qbq_wzk/.m2/repository/com/github/jnr/jnr-unixsocket/0.8/jnr-unixsocket-0.8.jar
[ERROR] urls[29] = file:/Users/qbq_wzk/.m2/repository/com/github/jnr/jnr-ffi/2.0.3/jnr-ffi-2.0.3.jar
[ERROR] urls[30] = file:/Users/qbq_wzk/.m2/repository/com/github/jnr/jffi/1.2.9/jffi-1.2.9.jar
[ERROR] urls[31] = file:/Users/qbq_wzk/.m2/repository/com/github/jnr/jffi/1.2.9/jffi-1.2.9-native.jar
[ERROR] urls[32] = file:/Users/qbq_wzk/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar
[ERROR] urls[33] = file:/Users/qbq_wzk/.m2/repository/org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.jar
[ERROR] urls[34] = file:/Users/qbq_wzk/.m2/repository/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar
[ERROR] urls[35] = file:/Users/qbq_wzk/.m2/repository/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar
[ERROR] urls[36] = file:/Users/qbq_wzk/.m2/repository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar
[ERROR] urls[37] = file:/Users/qbq_wzk/.m2/repository/com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar
[ERROR] urls[38] = file:/Users/qbq_wzk/.m2/repository/com/github/jnr/jnr-constants/0.8.7/jnr-constants-0.8.7.jar
[ERROR] urls[39] = file:/Users/qbq_wzk/.m2/repository/com/github/jnr/jnr-enxio/0.9/jnr-enxio-0.9.jar
[ERROR] urls[40] = file:/Users/qbq_wzk/.m2/repository/com/github/jnr/jnr-posix/3.0.12/jnr-posix-3.0.12.jar
[ERROR] urls[41] = file:/Users/qbq_wzk/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[42] = file:/Users/qbq_wzk/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.52/bcpkix-jdk15on-1.52.jar
[ERROR] urls[43] = file:/Users/qbq_wzk/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.52/bcprov-jdk15on-1.52.jar
[ERROR] urls[44] = file:/Users/qbq_wzk/.m2/repository/ch/qos/logback/logback-classic/1.2.1/logback-classic-1.2.1.jar
[ERROR] urls[45] = file:/Users/qbq_wzk/.m2/repository/ch/qos/logback/logback-core/1.2.1/logback-core-1.2.1.jar
[ERROR] urls[46] = file:/Users/qbq_wzk/.m2/repository/com/google/auth/google-auth-library-oauth2-http/0.6.0/google-auth-library-oauth2-http-0.6.0.jar
[ERROR] urls[47] = file:/Users/qbq_wzk/.m2/repository/com/google/auth/google-auth-library-credentials/0.6.0/google-auth-library-credentials-0.6.0.jar
[ERROR] urls[48] = file:/Users/qbq_wzk/.m2/repository/com/google/http-client/google-http-client/1.19.0/google-http-client-1.19.0.jar
[ERROR] urls[49] = file:/Users/qbq_wzk/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[50] = file:/Users/qbq_wzk/.m2/repository/com/google/http-client/google-http-client-jackson2/1.19.0/google-http-client-jackson2-1.19.0.jar
[ERROR] urls[51] = file:/Users/qbq_wzk/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar
[ERROR] urls[52] = file:/Users/qbq_wzk/.m2/repository/com/spotify/dockerfile-maven-extension/1.3.6/dockerfile-maven-extension-1.3.6.jar
[ERROR] urls[53] = file:/Users/qbq_wzk/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[54] = file:/Users/qbq_wzk/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar
[ERROR] urls[55] = file:/Users/qbq_wzk/.m2/repository/org/apache/maven/maven-builder-support/3.3.9/maven-builder-support-3.3.9.jar
[ERROR] urls[56] = file:/Users/qbq_wzk/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[57] = file:/Users/qbq_wzk/.m2/repository/com/google/inject/guice/4.0/guice-4.0-no_aop.jar
[ERROR] urls[58] = file:/Users/qbq_wzk/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[59] = file:/Users/qbq_wzk/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[60] = file:/Users/qbq_wzk/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
[ERROR] urls[61] = file:/Users/qbq_wzk/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.6/plexus-component-annotations-1.6.jar
[ERROR] urls[62] = file:/Users/qbq_wzk/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[63] = file:/Users/qbq_wzk/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[64] = file:/Users/qbq_wzk/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
[ERROR] urls[65] = file:/Users/qbq_wzk/.m2/repository/org/apache/maven/maven-archiver/3.0.0/maven-archiver-3.0.0.jar
[ERROR] urls[66] = file:/Users/qbq_wzk/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.jar
[ERROR] urls[67] = file:/Users/qbq_wzk/.m2/repository/org/codehaus/plexus/plexus-archiver/2.9.1/plexus-archiver-2.9.1.jar
[ERROR] urls[68] = file:/Users/qbq_wzk/.m2/repository/org/codehaus/plexus/plexus-io/2.4.1/plexus-io-2.4.1.jar
[ERROR] urls[69] = file:/Users/qbq_wzk/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : org.apache.commons.logging.LogFactory
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

------------------------------------------------------------------------------------------------------

<build>
		<finalName>eureka-server</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>dockerfile-maven-plugin</artifactId>
				<version>1.3.6</version>
				<configuration>
					<repository>${docker.image.prefix}/${project.artifactId}</repository>
					<buildArgs>
						<JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
					</buildArgs>
				</configuration>
				<executions>
					<execution>
						<id>default</id>
						<phase>install</phase>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			
		</plugins>
	</build>

The command to execute is like this.
mvn install --debug

It's a problem that's been bothering me for days, and it's fine on a Windows computer, but not on a MAC.

**Comment by jZ-Zj** [comment]
How do you solve this problem finally ?

**Comment by taoguoliang** [comment]
Have u solved it?

**Comment by chandinikhetawat** [comment]
@zhangshexin  How did you solve this problem?
