### ISSUE TITLE
Which version can I use?

### ISSUE THREAD

**Issue by nanquanyuhao** [spotify/dockerfile-maven#173]
[https://github.com/spotify/dockerfile-maven#authenticating-with-maven-pomxml
](https://github.com/spotify/dockerfile-maven#authenticating-with-maven-pomxml)

you say like this:
```
Since version 1.3.XX, you can authenticate using config from the pom itself. Just add configuration similar to:

<plugin>
    <groupId>com.spotify</groupId>
    <artifactId>dockerfile-maven-plugin</artifactId>
    <version>${version}</version>
    <configuration>
        <username>repoUserName</username>
        <password>repoPassword</password>
        <repository>${docker.image.prefix}/${project.artifactId}</repository>
        <buildArgs>
            <JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
        </buildArgs>
    </configuration>
</plugin>
```

But I have tried, I was faild... Thanks.

**Comment by davidxia** [comment]
Please provide more info on what failed, error message, stacktrace, repro steps, etc. It's hard to figure out what's going on with just the description above.

**Comment by nanquanyuhao** [comment]
@RyeGhost May be we have the same problem...

**Comment by RyeGhost** [comment]
@nanquanyuhao , I changed the version from 1.3.6 to 1.4.1. Then It works well. 
Hope that works for you, too.

 
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <version>1.4.1</version>
                <configuration>
                    <repository>${docker.image.prefix}/${project.artifactId}</repository>
                    <tag>${project.version}</tag>
                    <buildArgs>
                        <JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
                    </buildArgs>
                </configuration>
                <executions>
                    <execution>
                        <id>default</id>
                        <phase>install</phase>
                        <goals>
                            <goal>build</goal>
                            <goal>push</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>

**Comment by RyeGhost** [comment]
Congratulations to you. I tried it before.  But there is an error 'Element usename is not allowed here' which seems that there is no such property.

**Comment by RyeGhost** [comment]
Yes. That's why I tried it before.  I thought it should supports those properties too. But it is weird that does not works for me.

**Comment by nanquanyuhao** [comment]
@RyeGhost ... what can I do ...

**Comment by HADB** [comment]
Same problem. It doesn't work with username and password in pom.xml

**Comment by nanquanyuhao** [comment]
@RyeGhost @HADB Hello...

Today I tried it and I successed... please use the 1.4.4...
