### ISSUE TITLE
Using any external Docker Credentials Store (e.g., when using Azure az acr login) prevents using credentials from the POM file (MavenPomAuthSupplier)

### ISSUE THREAD

**Issue by mathiasslawik** [spotify/dockerfile-maven#176]
Hi,

I'm using an Azure Container Registry where I want to use dockerfile-maven to push Docker images to.

When using the `az acr login` Azure Command Line Tools command in Windows, Microsoft changes the Docker config.json to instruct Docker for Windows to use the Windows Credential Store to retrieve the password for the respective registry. For reference, the resulting Docker config.json looks like this:

```
{
	"auths": {
		"[My ACR Name].azurecr.io": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.03.0-ce (windows)"
	},
	"credsStore": "wincred"
}
```

I specified the credentials in the POM file and expected the MultiRegistryAuthSupplier to "fall through" to the MavenPomAuthSupplier. However, when the ConfigFileRegistryAuthSupplier first encounters this file, it falsely assumes that there are in fact authentication information, when in reality, they are unavailable as it cannot use the wincred provider. It returns empty credentals, leading to an unauthorized error.

I think the easiest way to solve similar issues would be to change the AbstractDockerMojo#createRegistryAuthSupplier() to FIRST add the MavenPomAuthSupplier and then add the ConfigFileRegistryAuthSupplier, as I'd expect people to be surprised when their POM settings would be overwritten by their Docker config instead of the other way around.

Otherwise, maybe the docker-client could be asked to not return empty authentication information, as this would also be the case when the credsStore is used on other operating systems, e.g., when using D-Bus Secret Service, macOS keychain or pass, see [the Docker reference](https://docs.docker.com/engine/reference/commandline/login/#credentials-store).

For now I'll try removing or setting a wrong path to the Docker config file as a workaround.

Best regards and thanks again for this nice Maven plugin,
Mathias

**Comment by mathiasslawik** [comment]
Ah, I just saw that MultiRegistryAuthSupplier#authForBuild() reverses the list of suppliers before going through them, so maybe I have a different issue. I'll update when I know more about my problem. Sorry for not noticing earlier.

**Comment by mathiasslawik** [comment]
I debugged the problem a bit more. I see now that the MultiRegistryAuthSupplier#authForBuild() is unrelated to this error.

When the Docker config.json has the mentioned format, the MultiRegistryAuthSupplier#authFor() method returns an AutoValue_RegistryAuth  instance that has username=null and password=null because the first added Supplier in AbstractDockerMojo#createRegistryAuthSupplier() is the ConfigFileRegistryAuthSupplier and not as I would have expected the MavenPomAuthSupplier.

So either dockerfile-maven could reverse the order in which the suppliers are added or this issue should be sent to spotify/docker-client.

Thanks a lot for considering this issue.

**Comment by mathiasslawik** [comment]
I can confirm that a workaround for this problem is specifying an invalid value for the dockerConfigFile configuration option.

**Comment by yuelipku** [comment]
I saw support for `credsStore` in https://github.com/spotify/docker-client .
Would  dockerfile-maven support  `credsStore` soon?
