### ISSUE TITLE
Publish all configuration paramers

### ISSUE THREAD

**Issue by nikita-clearscale** [spotify/dockerfile-maven#181]
Documentation contains some examples about plugin usage but there is no full description about all parameters in `<configuration>` section. E.g. it is unclear what full list of parameters your plugin expects.

Could oyu please add full list of parameters in `<configuration>` section to Readme.md file?

**Comment by dlucek** [comment]
This would be useful, if you show me what code is involved I will do the GitHub mark up.

Thanks.
