### ISSUE TITLE
Feature request: Overriding serverId when using useMavenSettingsForAuth

### ISSUE THREAD

**Issue by anton-johansson** [spotify/dockerfile-maven#185]
**FEATURE REQUEST**:

## Description

We use Nexus 3 as our repository, both for Maven artifacts and for Docker images. Docker does not allow hosting repositories on anything other than the root. Because of this, we have to use a different port for the Docker registry. We use 18443 for getting and 18444 for pushing.

My `settings.xml` file looks like this, since this is how it works for Maven artifacts:
```xml
        ...
        <server>
            <id>repository.example.com</id>
            <username>my-username</username>
            <password>{my-encrypted-password}</password>
        </server>
        ...
```

Now, for authentication to work using `useMavenSettingsForAuth`, I need to duplicate my server configuration, with the `id` named `repository.example.com:18444`. I would like to avoid this.

## Suggestion

When we [fetch the server name to use when looking up the credentials](https://github.com/spotify/dockerfile-maven/blob/master/plugin/src/main/java/com/spotify/plugin/dockerfile/MavenRegistryAuthSupplier.java#L59), can't we have another setting that overrides this? So I can force this server name in my `pom.xml`:
```xml
<useMavenSettingsForAuth>true</useMavenSettingsForAuth>
<serverId>repository.example.com</serverId>
```

I could do it myself and submit a PR if you lack time, but I'm not sure if it's the right approach.

**Comment by manikmagar** [comment]
I think I am stuck due to lack of this feature. I cannot control settings.xml in CI/CD pipeline. It will help if plugin allows to set server id.
