### ISSUE TITLE
support Dockerfile ARG & --build-arg <varname>=<value> 

### ISSUE THREAD

**Issue by lucwillems** [spotify/dockerfile-maven#186]
** FEATURE REQUEST?**: yes

support of Dockerfile ARG injection into the build
https://docs.docker.com/engine/reference/builder/#arg

## What do you expect

a list of Name/values we can inject into the build so DockerFile can use them to set
environment values. we like to use this to insert build information like git tags/sha1/buildhost/buildtime etc. this allows fast tracing what/which software build is running using plain environment variables
mostly used in CI pipelines where docker images have :latest tag until some more integration testing has been done , and final version tags are assigned to the released "latest" image.
at that point , the environment includes all build details for reference.

## Software:
ldocker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.5
 Git commit:   f4ffd2511ce9
 Built:        Wed Feb  7 15:07:19 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   f4ffd2511ce9
 Built:        Sat Oct 21 17:27:07 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by marceldiass** [comment]
hey @lucwillems 
I'm using this plugin and I'm passing build-args to it. Also I'm using `ARG` before and after the `FROM`.

Take a look in the example at Readme.  https://github.com/spotify/dockerfile-maven#example
