### ISSUE TITLE
[FEATURE REQUEST] Add support for .dockerignore

### ISSUE THREAD

**Issue by ghilainm** [spotify/dockerfile-maven#187]
## Description
There is currently no support for .dockerignore and the full content of the docker context directory is sent. If this directory is big it slow downs a lot the build. As a consequence I don't use the plugin anymore.

**Comment by yuelipku** [comment]
+1
It is impossible to build big projects with this.

**Comment by facboy** [comment]
it seems it sort of supports it if you look at `com.spotify.docker.client.CompressedDirectory`.  Unfortunately it seems it does not respect `**` like the 'real' docker does.

**Comment by m1t1l** [comment]
+1

**Comment by jcchavezs** [comment]
Please at least make it clear in the readme. This is an important feature of docker and trying to figure out why it does not work could spend someones time.
