### ISSUE TITLE
how to use an older image exists locally rather than pull the latest version from internet?

### ISSUE THREAD

**Issue by yuweiming2016** [spotify/dockerfile-maven#192]
when we build an images the docker server always attempt to pull a newer version of the image，even if there is already an image locally
 "docker-maven-plugin" can set `<pullOnBuild>false</pullOnBuild>` to 
but how to set when we use "dockerfile-maven" plugin?

**Comment by mattnworb** [comment]
set `<pullNewerImage>` to false

https://github.com/spotify/dockerfile-maven/blob/dd52149b61c5328b87a2bb9d67d12cdada077aa1/plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java#L77-L81
