### ISSUE TITLE
Enrich docker-info.jar with a generated java class.

### ISSUE THREAD

**Issue by tonicsoft** [spotify/dockerfile-maven#207]
FEATURE REQUEST

## Description

The docker-info jar would by much more helpful if it contained a java class with some static fields rather than some resource files (or in addition to). This would remove the need for lots of resource loading code which is tedious.

**Comment by tonicsoft** [comment]
I should add that I may be willing to contribute to this if there is general agreement that it's a good idea.

**Comment by mattnworb** [comment]
I'm not sure if I follow - what properties are your referring to? What type of IDE integration are you after?

**Comment by tonicsoft** [comment]
The properties I'm referring to are the meta-data files stored in the META-INF/docker directory of the docker-info artifact generated by the plugin. These are:
 * image-id
 * image-name
 * repository
 * tag

In terms of IDE integration, I would like to be able to run integration tests from the IDE. As an example, open the plugin/src/it/advanced project in Intellij IDEA, as a standalone project disconnected from the parent dockerfile-maven project. To get this to work as a standalone maven project you will need to replace the tokens for group Id, artifact Id and version that are resolved by the integration test runner.

If you try to run the MainIT from the IDEA, you will get a message like this:
```
java.lang.IllegalArgumentException: resource META-INF/docker/com.spotify.it/backend/image-name not found.
```
This is because Intellij has no knowledge of the fact that the plugin is building an extra jar which other projects are supposed to depend on. So essentially it fails to resolve the docker-info type dependency. 

Even running mvn install which will install the docker-info to your local repo does not help, although this might be because Intellij has an issue with using the "type" element of the dependency declaration, which is very unusual.

**Comment by tonicsoft** [comment]
Sorry I accidentally referred to docker-info containing a properties resource in the original description which I guess confused you. I meant the individual resource files for each property rather than a `.properties` file.
