### ISSUE TITLE
Adding support of option --force-rm in build command

### ISSUE THREAD

**Issue by rschlick** [spotify/dockerfile-maven#210]
**FEATURE REQUEST**: Adding support for option --force-rm in docker build

## Description

Old versions of Docker creates many intermediate images during image building.
There is an option **_--force-rm_** to remove all intermediate containers after building.

Example: docker build -t image_name -f Dockerfile . --force-rm

Could you integrate this option into the plugin ? 

**Example 1 (configuration with POM plugin):** 

` <plugin>
	<groupId>com.spotify</groupId>
	<artifactId>dockerfile-maven-plugin</artifactId>
	<version>1.4.4</version>
	<executions>
		<execution>
			<id>default</id>
			<goals>
				<goal>build</goal>
				<goal>push</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<forceRm>true</forceRm>                    
	</configuration>
</plugin>`

**Example 2 (configuration by command line):**

`mvn dockerfile:build -Ddockerfile.build.force-rm ` 

Thank you!

Romain

**Comment by Mikep86** [comment]
Can this issue be re-opened? It would be a very useful feature addition.
