### ISSUE TITLE
Could not acquire image ID or digest following build

### ISSUE THREAD

**Issue by yangguangftlp** [spotify/dockerfile-maven#216]
**Is this a BUG REPORT or FEATURE REQUEST?**:

## Description

[Add feature/bug description here]

## How to reproduce

[Add steps on how to reproduce this issue]

## What do you expect

[Describe what do you expect to happen]

## What happened instead

[Describe the actual results]

## Software:

- `docker version`: [Add the output of `docker version` here, both client and server]
- Spotify's dockerfile-maven version: [Add dockerfile-maven version here]

## Full backtrace

```text
[Paste full backtrace here]
```
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.4:build (default-cli) on project starfish-math-app: Execution default-cli of goal com.spotify:dockerfile-maven-plugin:1.4.4:build failed: Could not acquire image ID or digest following build -> [Help 1]

**Comment by sandymcp** [comment]
I got this when I had an ARG in the dockerfile which wasn't declared in buildargs of the plugin.

**Comment by php-coder** [comment]
In my case, it failed because `.dockerignore` file: https://github.com/spotify/dockerfile-maven/issues/25#issuecomment-310667051

**Comment by cdshah** [comment]
I had the following problem at my end. In my dockerfile, the maintainer was mis-spelled.
Please debug by trying to build the image using docker build -t <tag-name> .

**Comment by pradeepnnv** [comment]
Docker tag was having weird format. Not sure if dockerfile-maven plugin can report it.
Docker tag causing issues: `<repository>/repository:tagName`

**Comment by lincolnluiz** [comment]
For those who have this problem, try to check if the image can be built using the docker build command, I had this same error because my Dockerfile contained an incorrect instruction
