### ISSUE TITLE
push is error in 1.4.4

### ISSUE THREAD

**Issue by 595979101** [spotify/dockerfile-maven#220]
log is Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.4:push (default-cli) on project springboot-docker: Could not push image: denied: requested access to the resource is denied -> [Help 1]

**Comment by 595979101** [comment]
and if my private repository is https.Where are certificates configured

**Comment by mattnworb** [comment]
please take a look at https://github.com/spotify/dockerfile-maven/blob/master/docs/authentication.md
