### ISSUE TITLE
how to build 'latest' by default, but tag version specified in pom?

### ISSUE THREAD

**Issue by laur89** [spotify/dockerfile-maven#228]
**FR/question**: how to get `latest` docker image with default mvn package phase, but get it tagged to a version on deploy phase? My config has

```
                <configuration>
                    <repository>${docker.image.prefix}/${project.artifactId}</repository>
                    <tag>${project.version}</tag>
                </configuration>
```

which means `latest` image is never built/tagged; would it be possible to either

1. override `tag` version via command line option so we could specify we only want latest, or
2. make sure `latest` is always tagged in addition to whatever the version pom specifies;

Plugin ver `1.4.6`

**Comment by sysadmiral** [comment]
There are a couple of ways to do this in this issue thread here: https://github.com/spotify/dockerfile-maven/issues/10
