### ISSUE TITLE
Cannot push to two separate repositories

### ISSUE THREAD

**Issue by alijaza** [spotify/dockerfile-maven#234]
**Is this a BUG REPORT or FEATURE REQUEST?**:

bug

## Description

I am trying to push my image to two different remote repositories (Docker Hub and Google). I created two different executions, each with their own repository value, as such:

```                    
<execution>
                        <id>push-image-docker</id>
                        <goals>
                            <goal>push</goal>
                        </goals>
                        <configuration>
                            <googleContainerRegistryEnabled>false</googleContainerRegistryEnabled>
                            <repository>docker.io/PROJ/tasks</repository>
                            <tag>latest</tag>
                        </configuration>
                    </execution>
                    <execution>
                        <id>push-image-google</id>
                        <goals>
                            <goal>push</goal>
                        </goals>
                        <configuration>
                            <googleContainerRegistryEnabled>true</googleContainerRegistryEnabled>
                            <repository>gcr.io/PROJ/textrecruit/tasks</repository>
                            <tag>latest</tag>
                        </configuration>
                    </execution>
```

This doesn't seem to work - it only pushes to one repo.

## How to reproduce

See above

## What do you expect

I expect two pushes, each to their own repo.

## What happened instead

See above

## Software:

- `docker version`: 18.06.1-ce
- Spotify's dockerfile-maven version: 1.4.4

**Comment by alijaza** [comment]
So it looks like it works fine when running `mvn deploy` but does not work with `mvn dockerfile:build`

**Comment by mattnworb** [comment]
The ‘push’ goal is bound to the ‘deploy’ phase, so I think what you are seeing makes sense.
