### ISSUE TITLE
dockerfile:tag fails when configured to skip

### ISSUE THREAD

**Issue by mewalsh** [spotify/dockerfile-maven#237]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

## Description

When "skip" is configured and no "repository" is defined, the "tag" goal fails with an error.  Shouldn't this mirror the behavior of both "build" and "push", and not care whether "repository" is defined if it is skipped.

When repository is defined to some arbitrary value, the "tag" goal is skipped.

## How to reproduce

See attached pom.xml

mvn dockerfile:tag

## What do you expect

The "tag" goal should be skipped.

## What happened instead

An error is reported as it is looking for the "repository" value.

## Software:

- `docker version`:

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false
Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false

- Spotify's dockerfile-maven version: 1.4.7

[pom.zip](https://github.com/spotify/dockerfile-maven/files/2506379/pom.zip)

**Comment by deveth0** [comment]
This is an interesting issue. I have configured the plugin in my root project and added the skip=true configuration.
Nevertheless the root project does not build. I have to add the skipTag property
```
20:52:50 [INFO] --- dockerfile-maven-plugin:1.4.9:build (default-cli) @ foo.root ---
20:52:51 [INFO] Skipping execution because 'dockerfile.skip' is set
20:52:51 [INFO] 
20:52:51 [INFO] --- dockerfile-maven-plugin:1.4.9:tag (default-cli) @ foo.root ---
...
20:52:52 [ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.9:tag (default-cli) on project foo.root: The parameters 'repository' for goal com.spotify:dockerfile-maven-plugin:1.4.9:tag are missing or invalid -> [Help 1]
```

**Comment by mattnworb** [comment]
I believe `repository` is required by the tag mojo even when it is configured to be skipped because the Maven annotations don't have any way to model a conditional requirement for properties:

https://github.com/spotify/dockerfile-maven/blob/a3e2951a67196f55bf2e0fa1a889bfbf19192279/plugin/src/main/java/com/spotify/plugin/dockerfile/TagMojo.java#L45

the "skip" behavior is implemented by just checking a property in the mojo code and doing an early `return` when it is set to true.
