### ISSUE TITLE
How to configure docker build options like --network

### ISSUE THREAD

**Issue by MeeraMakadia** [spotify/dockerfile-maven#254]
dockerfile-maven-plugin = 1.4.4
docker version = Docker version 18.06.0-ce, build 0ffa825

I want to run following command
docker build --build-arg proxy=${jenkinsProxy} -t ${dockerRepo}:${dockerRepoTag} --network=host

So please guild how to configure --network and proxy as well.

I couldn't find any example for --network option or how to provide any other option.

Thanks
Meera

**Comment by suesunss** [comment]
is it supported now ?

**Comment by realn0whereman** [comment]
Can this be re-opened? 

Without this, I have to manually go build docker containers once the mvn step fails, and hope it remains cached for a while.

**Comment by lukemorrill** [comment]
Also looking for this feature...
