### ISSUE TITLE
Building docker image fails when using parent in pom

### ISSUE THREAD

**Issue by martijnhiemstra** [spotify/dockerfile-maven#256]
I used to have a maven project that didn't have a parent. In that projects pom.xml I have the following:

    <build>
    <plugins>
    <plugin>
	<groupId>com.spotify</groupId>
	<artifactId>dockerfile-maven-plugin</artifactId>
	<version>1.3.6</version>
	<configuration>
	    <repository>slimrecepten/${project.artifactId}</repository>
 	    <buildArgs>
	        <JAR_FILE>${project.build.directory}/${project.build.finalName}.jar</JAR_FILE>
	    </buildArgs>
            <tag>${project.version}</tag>
	</configuration>
    </plugins>
    </plugin>
    </build>

Now I have build multiple projects so I decided to create a single parent pom. I move the plugin part to the parent pom. When I execute the mvn dockerfile:build command I get an error:

    COPY failed: stat /var/lib/docker/tmp/docker-builder911947032/home/me/Projects/Users/target/myproject.jar

The plugin is trying to copy from the docker tmp directory which is wrong! It looks like if you use a parent pom when the plugin doesn't work anymore.

**Comment by DrFaust92** [comment]
i recommend changing it to <pluginManagement> instead of <plugin> in the parent pom
this way you can call it only in the children you need while having a centralized place that manages config

see example:

parent pom:
```xml
<build>
    <pluginManagement>
        <plugins>
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <version>1.4.10</version>
                <executions>
                    <execution>
                        <id>tag-version</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>build</goal>
                            <goal>tag</goal>
                            <goal>push</goal>
                        </goals>
                        <configuration>
                            <tag>${project.version}</tag>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <repository>${docker.prefix}/${project.artifactId}</repository>
                </configuration>
            </plugin>
        </plugins>
    </pluginManagement>
</build>
```


child pom:

```xml
<build>
	<plugins>
		<plugin>
			<groupId>com.spotify</groupId>
			<artifactId>dockerfile-maven-plugin</artifactId>
		</plugin>
	</plugins>
</build>
```
