### ISSUE TITLE
feature request: support building with kaniko

### ISSUE THREAD

**Issue by paulczar** [spotify/dockerfile-maven#263]
## Description

Kaniko is a tool from google that lets you build docker images without needing a running docker daemon.  this can be very useful in CI/CD scenarios and when used inside kubernetes clusters.  It would be great if you supported using kaniko as an alternative to `docker build`.

see https://github.com/GoogleContainerTools/kaniko

**Comment by cricket007** [comment]
Since this is a Maven Plugin, I don't think using kaniko, a Golang program would be useful. 

If anything, [Jib (core)](https://github.com/GoogleContainerTools/jib/tree/master/jib-core) should be used.
