### ISSUE TITLE
Custom nested Dockerfile location fails using Windows

### ISSUE THREAD

**Issue by sdahlberg** [spotify/dockerfile-maven#267]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

## Description

Building image using custom nested dockerfile location fails on Windows.

## How to reproduce

- install docker-toolbox
- in pom supply custom location like `<dockerfile>src/main/docker/Dockerfile</dockerfile>`
- watch build fail with:
```
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:build (default-cli) on project x: Execution default-cli of goal com.spotify:dockerfile-maven-plugin:1.4.10:build failed: Could not acquire image ID or digest following build -> [Help 1]
```
- watch log inside docker machine (/var/lib/boot2docker/log/docker.log):
```
time="2019-01-27T21:32:18.399617116Z" level=error msg="Handler for POST /build returned error: Cannot locate specified Dockerfile: src\\main\\docker\\Dockerfile"
```
See DockerClient:
```
    public static BuildParam dockerfile(final Path dockerfile) {
      return create("dockerfile", dockerfile.toString());
    }
```
Path.toString() will return backslashes and placed as such in query string.

## What do you expect

No windows back slashes in call to docker machine.

## What happened instead

See steps to reproduce. Build failed.

## Software:
- Spotify's dockerfile-maven version: [1.4.10]

**Comment by Rene-76** [comment]
I currently have the same issue. For now I worked around it with the maven-resource-plugin by moving the respective Dockerfile from the nested location to the "project.build.directory".

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <executions>
        <execution>
            <id>copy-docker-resources</id>
            <phase>prepare-package</phase>
            <goals>
                <goal>copy-resources</goal>
            </goals>
            <configuration>
                <outputDirectory>${project.build.directory}</outputDirectory>
                <resources>
                    <resource>
                        <directory>${project.basedir}/src/main/docker</directory>
                        <filtering>false</filtering>
                    </resource>
                </resources>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by Whotakesmyname** [comment]
I think this is kind of critical bug, but the fix should not be complex. Will PR be accepted?
