### ISSUE TITLE
Maven dockerfile plugin does not respect DOCKER_HOST 's ssh capabilities

### ISSUE THREAD

**Issue by planetf1** [spotify/dockerfile-maven#272]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

## Description
java.net.UnknownHostException when DOCKER_HOST is set to an ssh endpoint, making use of aliases in ~/.ssh/config

[Add feature/bug description here]

## How to reproduce
* Create a maven project that uses dockerfile-maven 1.4.10
* configure docker to make use of a remote host for example by
** Adding this to ~/.ssh/config
Host devc
  HostName 158.176.66.122
  IdentityFile ~/Box/keys/id_ecdsa
  Port 22
  User jonesn
** In environment export DOCKER_HOST=ssh://devc
** checking docker commands work - build, run an image

Now try and build the maven project with mvn clean deploy

An error will occur similar to:

```

[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:build (default) on project open-metadata-docker: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.net.UnknownHostException: devc: Unknown host devc -> [Help 1]

12:10 $ env | grep DOCKER
DOCKER_HOST=ssh://devc
```

[Add steps on how to reproduce this issue]

## What do you expect

The docker build to work correctly.

[Describe what do you expect to happen]

## What happened instead

Network/host not found error

[Describe the actual results]

See transcript above
## Software:

- `docker version`: [Add the output of `docker version` here, both client and server]
```
15:31 $ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 Kubernetes:
  Version:          Unknown
  StackAPI:         Unknown
```
- Spotify's dockerfile-maven version: [Add dockerfile-maven version here]
1.4.10

## Full backtrace

```text
[Paste full backtrace here]
```

NOTE. If DOCKER_HOST is unset - ie to use local docker daemon - no errors occur

I then tried changing ~/.ssh/config so that the name of the entry was the IP address 

The result then was
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:build (default) on project open-metadata-docker: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: com.spotify.docker.client.shaded.org.apache.http.conn.HttpHostConnectException: Connect to 158.176.66.122:2375 [/158.176.66.122] failed: Connection refused (Connection refused) -> [Help 1]

(and another similar full stack trace)

The implication is that the docker plugin is not respecting the functionality of DOCKER_HOST with respect to ssh configuration - which in my case I'm using primarily due to resource constraint to offload the IO/cpu intensive docker steps to a cloud based machine.

**Comment by planetf1** [comment]
Posted more complete stack trace from original error at https://gist.github.com/1059280431d2c3f43dc92acb226b0a39

**Comment by mmiglier** [comment]
Not working yet

**Comment by youurayy** [comment]
not working, can we reopen?

**Comment by bcoughlan** [comment]
As an alternative I made a little script to work around this: https://github.com/bcoughlan/docker-ssh-bridge/

```
docker-ssh-bridge user@host -- mvn install
```
