### ISSUE TITLE
Authentication for push fails on MacOS

### ISSUE THREAD

**Issue by planetf1** [spotify/dockerfile-maven#273]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

## Description

[Add feature/bug description here]

## How to reproduce
* MacOS + Docker CE (current levels)
* latest dockerfile-maven plugin (1.4.10)
* Ensure logged in to docker (docker login) and can build/run images manually

Attempt to build/push an image using a pom utilizing this plugin:

Dockerfile builds ok
then...

[Add steps on how to reproduce this issue]

## What do you expect
Dockerfile is pushed

[Describe what do you expect to happen]

## What happened instead
Dockerfile is not pushed
```
[INFO] Successfully built planetf1/atlas-init-egeria:1.1-SNAPSHOT
[INFO]
[INFO] --- dockerfile-maven-plugin:1.4.10:push (default) @ open-metadata-docker ---
[INFO] The push refers to repository [docker.io/planetf1/atlas-init-egeria]
[INFO] Image 8ebf2c637a73: Preparing
[INFO] Image c961ebb25158: Preparing
[INFO] Image 4b7d93055d87: Preparing
[INFO] Image 663e8522d78b: Preparing
[INFO] Image 283fb404ea94: Preparing
[INFO] Image bebe7ce6215a: Preparing
[INFO] Image bebe7ce6215a: Waiting
[ERROR] denied: requested access to the resource is denied
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not push image
    at com.spotify.plugin.dockerfile.PushMojo.execute (PushMojo.java:90)
    at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute (AbstractDockerMojo.java:265)
...
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: com.spotify.docker.client.exceptions.DockerException: denied: requested access to the resource is denied
    at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError (LoggingProgressHandler.java:105)
...
[INFO] The push refers to repository [docker.io/planetf1/atlas-init-egeria]
[INFO] Image 8ebf2c637a73: Preparing
[INFO] Image c961ebb25158: Preparing
[INFO] Image 4b7d93055d87: Preparing
[INFO] Image c961ebb25158: Waiting
[INFO] Image 663e8522d78b: Preparing
[INFO] Image 283fb404ea94: Preparing
[INFO] Image bebe7ce6215a: Preparing
[INFO] Image bebe7ce6215a: Waiting
[ERROR] denied: requested access to the resource is denied
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:44 min
[INFO] Finished at: 2019-02-21T15:58:44Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:push (default) on project open-metadata-docker: Could not push image: denied: requested access to the resource is denied -> [Help 1]
...
```

[Describe the actual results]
As above ... but note then that a manual push works fine:
```
15:58 $ docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
planetf1/atlas-init-egeria           1.1-SNAPSHOT        066c93a04ac3        52 seconds ago      854MB
<none>                               <none>              ea3429a3a9f1        4 hours ago         854MB
ubuntu                               18.04               47b19964fb50        2 weeks ago         88.1MB
docker/kube-compose-controller       v0.4.18             47df7579c5fc        5 weeks ago         30.6MB
docker/kube-compose-api-server       v0.4.18             e73645df5dc6        5 weeks ago         47.8MB
k8s.gcr.io/kube-proxy                v1.13.0             8fa56d18961f        2 months ago        80.2MB
k8s.gcr.io/kube-controller-manager   v1.13.0             d82530ead066        2 months ago        146MB
k8s.gcr.io/kube-scheduler            v1.13.0             9508b7d8008d        2 months ago        79.6MB
k8s.gcr.io/kube-apiserver            v1.13.0             f1ff9b7e3d6e        2 months ago        181MB
k8s.gcr.io/coredns                   1.2.6               f59dcacceff4        3 months ago        40MB
k8s.gcr.io/etcd                      3.2.24              3cab8e1b9802        5 months ago        220MB
k8s.gcr.io/pause                     3.1                 da86e6ba6ca1        14 months ago       742kB
✔ ~/src/egeria/open-metadata-resources/open-metadata-deployment/docker/atlas-init [helm20|●2✚ 6⚑ 20]
15:59 $ docker push planetf1/atlas-init-egeria:1.1-SNAPSHOT
The push refers to repository [docker.io/planetf1/atlas-init-egeria]
8ebf2c637a73: Pushed
c961ebb25158: Pushed
4b7d93055d87: Mounted from library/ubuntu
663e8522d78b: Mounted from library/ubuntu
283fb404ea94: Mounted from library/ubuntu
bebe7ce6215a: Mounted from library/ubuntu
1.1-SNAPSHOT: digest: sha256:bb03dded79b4678e3aa69d4bc78a89052f67eb253fc7c7267224fbe9f061b3e6 size: 1571
✔ ~/src/egeria/open-metadata-resources/open-metadata-deployment/docker/atlas-init [helm20|●2✚ 6⚑ 20]
```

My docker configuration for auth includes:
```
16:04 $ cat ~/.docker/config.json
{
	"auths": {
		"https://index.docker.io/v1/": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.09.2 (darwin)"
	},
	"credsStore": "osxkeychain",
	"stackOrchestrator": "kubernetes"
}
```
which maybe where the error is caused.

Note that I recently raised #272 as I was originally trying to run docker remotely - which didn't work either.

## Software:

- `docker version`: [Add the output of `docker version` here, both client and server]
```
16:10 $ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 Kubernetes:
  Version:          Unknown
  StackAPI:         Unknown
```
- Spotify's dockerfile-maven version: [Add dockerfile-maven version here]
1.4.10
## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by planetf1** [comment]
By removing
```
	"credsStore": "osxkeychain",
```
from ~/.docker/config.json, and the rerunning
```
docker login
```
The password is then stored base64 encoded instead.

I then reran the maven build, and this time the image was pushed correctly.

My conclusion is therefore that the plugin is not supportable the pluggable authentication - osx credential store here, which is in fact the *default* for MacOS, and quite typical for developers on this platform therefore.

Can I suggest

* Some thought is given to whether this can be added into the readme as a caveat in the short term
* Consideration as to whether the error message on push can be improved .include this as a possibility
* looking at whether this default config can be supported (and check other platforms like windows too)

**Comment by cerker** [comment]
I suddenly got a similar problem but the plugin fails when building the image with the following message:

`
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not build image
    at com.spotify.plugin.dockerfile.BuildMojo.buildImage (BuildMojo.java:234)
...
Caused by: com.spotify.docker.client.exceptions.DockerException: com.spotify.docker.client.shaded.com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'The': was expecting ('true', 'false' or 'null')
 at [Source: (String)"The user name or passphrase you entered is not correct."; line: 1, column: 4]
    at com.spotify.docker.client.auth.ConfigFileRegistryAuthSupplier.authForBuild (ConfigFileRegistryAuthSupplier.java:108)
`

After removing the `"credsStore": "osxkeychain"` line as proposed by planetf1, it works.

**Comment by tbotting** [comment]
> By removing
> 
> ```
> 	"credsStore": "osxkeychain",
> ```
> 
> from ~/.docker/config.json, and the rerunning
> 
> ```
> docker login
> ```
> 
> The password is then stored base64 encoded instead.
> 
> I then reran the maven build, and this time the image was pushed correctly.
> 
> My conclusion is therefore that the plugin is not supportable the pluggable authentication - osx credential store here, which is in fact the _default_ for MacOS, and quite typical for developers on this platform therefore.
> 
> Can I suggest
> 
> * Some thought is given to whether this can be added into the readme as a caveat in the short term
> * Consideration as to whether the error message on push can be improved .include this as a possibility
> * looking at whether this default config can be supported (and check other platforms like windows too)

I'd just like to add that the same happened to me on Windows. Simply removing 'credsStore' property and its value, then logging in again worked flawlessly!
