### ISSUE TITLE
Getting maven build fail with 1.3.0 version

### ISSUE THREAD

**Issue by freesoft** [spotify/dockerfile-maven#28]
Hello, I'm getting this error with 1.3.0 version, but no problem with 1.2.2. Is it known issue or something I need to change my configuration?

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.0:build (default) on project server: Execution default of goal com.spotify:dockerfile-maven-plugin:1.3.0:build failed: Plugin com.spotify:dockerfile-maven-plugin:1.3.0 or one of its dependencies could not be resolved: Could not find artifact com.spotify:docker-client:jar:shaded:8.7.1 in repo (OUR INTERNAL REPO that MIRRORS public one) -> [Help 1]

**Comment by mattnworb** [comment]
I would guess there is something going on with your internal repo, or that its mirroring setup is not up-to-date, as you can see that [that artifact is available in Maven Central](http://repo1.maven.org/maven2/com/spotify/docker-client/8.7.1/)
