### ISSUE TITLE
have -Ddockerfile.skip=false ?

### ISSUE THREAD

**Issue by maojx0630** [spotify/dockerfile-maven#283]
![image](https://user-images.githubusercontent.com/37826107/55406760-52d6bd80-558f-11e9-835c-e25ab741d450.png)
![image](https://user-images.githubusercontent.com/37826107/55406835-7a2d8a80-558f-11e9-80c0-5281577f7f3b.png)
I hope that the default situation is not packaged, only using dockerfile: build to pack, what is the way to achieve it?

**Comment by huahaofeng** [comment]
Try to remove your <executions> section, then the plugin will not execute during package phase.

**Comment by 12monkey12** [comment]
+1 I have the same trouble
it do not wrok
`<executions>
                    <execution>
                        <id>build-image</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>`
`mvn dockerfile:build`

--- dockerfile-maven-plugin:1.4.9:build (build-image) @ log-server ---
[INFO] Skipping execution because 'dockerfile.skip' is set

it work
`<executions>
                    <execution>
                        <id>build-image</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>`
`mvn -Ddockerfile.skip=false dockerfile:build`
