### ISSUE TITLE
How to customize the Docker host URL in the configuration file?

### ISSUE THREAD

**Issue by mmm8955405** [spotify/dockerfile-maven#285]
I'm missing the way to configure a remote docker host daemon to deploy to.
The other maven plugin provided a way to configure it. Now I cannot find a way to do so:

Old Plugin:

<configuration>
    
    <dockerHost>http://localhost:2375</dockerHost>
    <imageName>${project.build.finalName}</imageName>
    <dockerDirectory>.</dockerDirectory>
</configuration>
Am trying to use for this now but surely it's wrong. The README.md did not provide any informationen how to do it.

Can anybody point me out to the solution?

I think it should be possible to configure remote hosts in plug-ins rather than in environment variables.

It's a terrible thing to do.

**Comment by mattnworb** [comment]
@mmm8955405 in general we think it makes the most sense for a configuration that could be custom per developer and per machine - the address at which to talk to the Docker daemon - to be configured elsewhere from your pom.xml, but whenever you find something “terrible” about an open source project you should feel free to create a pull request to add the feature you’d like to have.

**Comment by mmm8955405** [comment]
thank you very much.
