### ISSUE TITLE
buildArgs encoding is converting spaces to +

### ISSUE THREAD

**Issue by thibgc** [spotify/dockerfile-maven#286]
The stale bot kept marking #136 stale because the OP did not receive any response, and eventually they gave up regularly bumping the thread and the stale bot closed it. **But #136 is still a problem**, and new user comments are going to a closed issue. I'm opening this in the hope it'll receive attention.

I have nothing to report that isn't already perfectly reported by the OP and their reproducible example. We use build args as the value of LABEL directives, and all spaces get replaced by + signs. The OP's problem is worse because they use the build arg as the value of an EXPOSE directive.

Any chance this will be addressed?

**Comment by jrmcdonald** [comment]
As commented in #136 this issue is also affecting me when passing values such as the project description to labels in an image.

**Comment by antoniolmc83** [comment]
I'm also affected, any chance to have a fix for this issue?

**Comment by graham2071** [comment]
Also affected by this issue.

**Comment by inetshell** [comment]
Also affected, did anyone found a workaround for it?

**Comment by thibgc** [comment]
@graham2071 @inetshell thanks for nudging this out of stale state :-) There has not been any activity in this thread from developers or workarounds proposed.

**Comment by graham2071** [comment]
Not sure why plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java treats buildArgs as URL (it uses `URLEncoder.encode` which converts spaces to +).

**Comment by thibgc** [comment]
No, stalebot.

**Comment by thibgc** [comment]
No...

**Comment by pmargreff** [comment]
Same problem here.

**Comment by wajda** [comment]
The issue is still valid. Is there any update on this?
