### ISSUE TITLE
add goal to save image tarball

### ISSUE THREAD

**Issue by petteyg** [spotify/dockerfile-maven#287]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

## Description

Add a goal to save the image tarball (but not attach it to the project) so that I can later call another plugin than scans it for security issues.

**Comment by Smiche** [comment]
Interested in that as well. Docker-maven-plugin has that feature.

**Comment by petteyg** [comment]
Feature requests don't go stale, silly bot.

**Comment by Smiche** [comment]
#330 adds that feature
