### ISSUE TITLE
 Could not push image

### ISSUE THREAD

**Issue by Skqing** [spotify/dockerfile-maven#291]
mvn dockerfile:push

[Add feature/bug description here]

## How to reproduce

[Add steps on how to reproduce this issue]

 push image succcess

[Describe what do you expect to happen]

 push image failed

[Describe the actual results]

## Software:

- Spotify's dockerfile-maven version: 1.4.10

## Full backtrace

```text
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:push (default-cli) on project new-demo-main: Could not push image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.Pro
cessingException: com.spotify.docker.client.shaded.org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect -> [Help 1]

```

**Comment by php-coder** [comment]
It seems like the plugin can't connect to the Docker. Is it running? Is it configured to listen on a port (rather than on a socket)?
