### ISSUE TITLE
Could not push image: unauthorized: authentication required

### ISSUE THREAD

**Issue by jayzch** [spotify/dockerfile-maven#300]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
## Description
    <build>
        <plugins>
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <version>${dockerfile-maven-version}</version>
                <configuration>
                    <dockerfile>./</dockerfile>
        <username>u</username>
        <password>p</password>
                    <repository>dockerhub.qingcloud.com/gksw_dev/dtop</repository>
                    <tag>${project.version}</tag>
                    <buildArgs>
                        <JAR_FILE>${project.build.finalName}.jar</JAR_FILE>
                    </buildArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

## How to reproduce

 mvn dockerfile:push
or 
mvn dockerfile:push -Ddockerfile.username=u -Ddockerfile.password=p
```
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:push (default-cli) on project mcc-boot-sc: Could not push image: unauthorized: authentication required -> [Help 1]
[ERROR] 
```
## What do you expect

Authenticating with maven pom.xml

## What happened instead

but using the same authentication  with maven settings.xml , it works.
```
        <plugins>
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <version>${dockerfile-maven-version}</version>
                <configuration>
                    <dockerfile>./</dockerfile>
                    <useMavenSettingsForAuth>true</useMavenSettingsForAuth>
                    <repository>dockerhub.qingcloud.com/gksw_dev/dtop</repository>
                    <tag>${project.version}</tag>
                    <buildArgs>
                        <JAR_FILE>${project.build.finalName}.jar</JAR_FILE>
                    </buildArgs>

                </configuration>
            </plugin>
        </plugins>
```

## Software:

docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T03:00:29+08:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"

**Comment by michael-wirth** [comment]
I solved the issue by changing the password. In my case it looks like the spotify:docker-client has problems with auto-generated passwords which contains special characters. I guess the "?" caused trouble in my case.

**Comment by HerrSvenson** [comment]
@michael-wirth Thank you so much!!! I spend half a day to find out what I did wrong, until I found your post.

**Comment by jayzch** [comment]
> @michael-wirth Thank you so much!!! I spend half a day to find out what I did wrong, until I found your post.

So It is ok after changed the password? @HerrSvenson

**Comment by HerrSvenson** [comment]
Yes I had a question and exclamation mark in my password, after changing it everything worked perfectly 👍
