### ISSUE TITLE
怎么配置docker客户端Cert

### ISSUE THREAD

**Issue by shipengzhen** [spotify/dockerfile-maven#304]
**Is this a BUG REPORT or FEATURE REQUEST?**:

## Description

[Add feature/bug description here]

## How to reproduce

[Add steps on how to reproduce this issue]

## What do you expect

[Describe what do you expect to happen]

## What happened instead

[Describe the actual results]

## Software:

- `docker version`: [Add the output of `docker version` here, both client and server]
- Spotify's dockerfile-maven version: [Add dockerfile-maven version here]

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by jiangweiguo** [comment]
配置系统环境变量

DOCKER_CERT_PATH=证书路径
DOCKER_HOST=https://xx.xx.xx:2376


win10 重启才生效

**Comment by feiyingmm** [comment]
> 配置系统环境变量
> 
> DOCKER_CERT_PATH=证书路径
> DOCKER_HOST=https://xx.xx.xx:2376
> 
> win10 重启才生效

我的win7, 配置了后一直没生效找了半天才看到这个回答, 重启了下果然好使
