### ISSUE TITLE
[1.4.12] Private repository with port number not valid anymore

### ISSUE THREAD

**Issue by mmaeller** [spotify/dockerfile-maven#308]
## Description

Private repository with port in address invalid.

## How to reproduce

https://myrepo:5001/project

## What do you expect

Port is a valid part of the repository URL.

## What happened instead
```
Repo name "myrepo:5001/project" must contain only lowercase, numbers, '-', '_' or '.'
```

See https://github.com/spotify/dockerfile-maven/commit/c0ce28f2050ad558946d394648d8bf70371c1509

**Comment by buhuan192** [comment]
only  80 port!

**Comment by mmaeller** [comment]
@buhuan192 Can you tell us why?

**Comment by SkySonR** [comment]
https://github.com/mmaeller/dockerfile-maven/commits?author=seamonstr
...

**Comment by mmaeller** [comment]
I don't get it.

**Comment by deveth0** [comment]
@buhuan192 bullshit, this would mean no ssl/tls...

@mmaeller  I think @SkySonR just wanted to point out the relevant changes which cause this issue. I completely agree, that this is a must have as most companies I work with also use custom private repositories which might be hosted on the same hostname but different ports.

**Comment by MatanRubin** [comment]
We're seeing the exact same issue, can't use a private repository with a custom port (which, as said above, is a very common use-case).
Looks like the issue can be easily fixed by changing `VALID_REPO_REGEX`

**Comment by seamonstr** [comment]
@mmaeller has got a good fix to this in his branch [with a PR pending](https://github.com/spotify/dockerfile-maven/pull/309).

**Comment by buhuan192** [comment]
String VALID_REPO_REGEX = "^([a-z0-9_.-])+(\\/[a-z0-9_.-]+)*$";  
You are right!
See if the next version can solve this little problem.

**Comment by dmonti** [comment]
This bug have appeared in v1.4.11 and still happening in v1.4.12

**Comment by SlipstreamZA** [comment]
Any idea when the pull request will get merged? Unable to use this with a private repository on a different port at the moment
