### ISSUE TITLE
1.4.11 / 1.4.12 missing in CHANGELOG

### ISSUE THREAD

**Issue by geoffreywiseman** [spotify/dockerfile-maven#310]
Neither 1.4.11 nor 1.4.12 appear in the CHANGELOG currently.

**Comment by geoffreywiseman** [comment]
This issue is still accurate — and not something particularly easy for an outsider to fix. ;)

**Comment by mattnworb** [comment]
I'll take care of this, thanks for reporting.

**Comment by mattnworb** [comment]
will be fixed in #324
