### ISSUE TITLE
dockerfile-maven plugin does not allow to configure Docker host

### ISSUE THREAD

**Issue by ketoor** [spotify/dockerfile-maven#311]
**FEATURE REQUEST**:

## Description

Old, docker-maven plugin, allows user to define (via Maven configuration) which Docker host should be used.
https://github.com/spotify/docker-maven-plugin/blob/dc265af355ac8e561b4f7b0eef35af52591c99da/src/main/java/com/spotify/docker/AbstractDockerMojo.java#L168
New, dockerfile-maven plugin, fetches this configuration from environment variables, especially from DOCKER_HOST.
However, on CI environments, we cannot use DOCKER_HOST variable - we have Docker installed locally on the machine, but some images should be build on remote Docker server.
Especially, current implementation does not allow to build images on two different Docker servers.

## How to reproduce

Two dockerfile-maven plugin definitions, to different images, that should be build on different Docker hosts.

## What do you expect

Be able to define Docker host using Maven configuration.

## What happened instead

Only configuration from environment variables is accepted.

## Software:

- `docker version`:
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:58 2018
 OS/Arch:           linux/amd64
 Experimental:      false

 

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:24 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
- Spotify's dockerfile-maven version: 1.4.10

**Comment by mmm8955405** [comment]
I also mentioned this question, but I don't know how the author thinks about it.
https://github.com/spotify/dockerfile-maven/issues/285
