### ISSUE TITLE
Support buildkit builds

### ISSUE THREAD

**Issue by dominikzalewski** [spotify/dockerfile-maven#313]
**FEATURE REQUEST**:

## Description

Support building with new buildkit: https://docs.docker.com/develop/develop-images/build_enhancements/

The reason why I need this is NOT only because the buildkit is faster and supports many new features. But mainly because the 'old' builder has a nasty bug described here:

https://github.com/moby/moby/issues/3639

where mapping VOLUMES from inherited Dockerfile does not work as expected. I am affraid they have no intention to fix it and the recommendation (as you can read in the thread) is to use the new buildkit.

## How to reproduce

When /etc/docker/daemon.json has { "features": { "buildkit": true } } or if I set environment variable DOCKER_BUILDKIT=1, neither of them is respected by the plugin.

## What do you expect

Either introduce a parameter in pom.xml for the plugin, or respect buildkit global options.

## What happened instead

Old builder is used.

## Software:

- `docker version`: Docker version 18.09.6, build 481bc77
- Spotify's dockerfile-maven version: 1.4.1

**Comment by phulei** [comment]
This seems to be still an issue , can someone update ?

**Comment by rafis** [comment]
Still can't manage to get it work:

> [ERROR] the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled

It should be enabled client-side, it is not possible to force from server-side. Also dockerfile-maven-plugin ignores settings set in `~/.docker/config.json` and even global environment variables `/etc/environment`.
