### ISSUE TITLE
How do I push to a specified private image repository

### ISSUE THREAD

**Issue by ChangMuChen** [spotify/dockerfile-maven#315]
**Is this a BUG REPORT or FEATURE REQUEST?**:

## Description
I try to add the url of the docker private repository in repository, but it always fails validation.The configuration is as follows:
```pom
<plugin>
    <groupId>com.spotify</groupId>
    <artifactId>dockerfile-maven-plugin</artifactId>
    <version>1.4.12</version>
    <configuration>
        <skipDockerInfo>true</skipDockerInfo>
        <username>docker-dev</username>
        <password>NP123456</password>
        <contextDirectory>${project.basedir}</contextDirectory>
        <repository>172.16.50.96:5432/${project.artifactId}</repository>
        <tag>${project.version}</tag>
        <buildArgs>
            <ARTIFACT>target/${project.build.finalName}.${project.packaging}</ARTIFACT>
        </buildArgs>
    </configuration>
</plugin>
```
Error message:
```
Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.12:build (default-cli) on project demo: Repo name "172.16.50.96:5432/demo" must contain only lowercase, numbers, '-', '_' or '.'.
```
## What do you expect

I wanted to find a way to push the image to a docker private repository

**Comment by ChangMuChen** [comment]
我现在能想到的便是填写hostname,然后修改docker主机中的host文件，以此来指向实际的仓库地址

**Comment by mmaeller** [comment]
@ChangMuChen 
See https://github.com/spotify/dockerfile-maven/issues/308 and https://github.com/spotify/dockerfile-maven/pull/309

**Comment by unmwww** [comment]
Use previous versions of 1.4.10

**Comment by beirtipol** [comment]
Is there any reason for delaying pulling the above changes in and releasing?
