### ISSUE TITLE
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.11:build (create_docker_image)

### ISSUE THREAD

**Issue by KristijanL** [spotify/dockerfile-maven#320]
BUG REPORT

## Description

version 1.4.11 and greater fails with an error

## How to reproduce

use configuration in pom.xml
<repository>private.repo.local:18445/application</repository>

## What do you expect

with version 1.4.10 and below it works
[INFO] BUILD SUCCESS

## What happened instead

[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.11:build (create_docker_image) on project crypto_service: Repo name "private.repo.local:18445/application" must contain only lowercase, numbers, '-', '_' or '.'. -> [Help 1]

## Software:

- Spotify's dockerfile-maven version: 1.4.11 / 1.4.12

**Comment by mattnworb** [comment]
fixed by #309

**Comment by mattnworb** [comment]
1.4.13 should have the fix mentioned above, should be in Maven Central soon.
