### ISSUE TITLE
multiple profiles, only one is build

### ISSUE THREAD

**Issue by KristijanL** [spotify/dockerfile-maven#326]
BUG REPORT

## Description

if you define multiple build profiles, and start maven with
mvn -f pom.xml package -B -am -P profile1,profile2
only one docker image will get build.

## How to reproduce

pom.xml configuration:

    <profiles>
        <profile>
            <id>docker-production</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.spotify</groupId>
                        <artifactId>dockerfile-maven-plugin</artifactId>
                        <configuration>
                            <skipDockerInfo>true</skipDockerInfo>
                            <dockerfile>docker/Dockerfile-production</dockerfile>
                            <repository>private:18445/application</repository>
                            <tag>PROD-${project.version}</tag>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>docker-develop</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.spotify</groupId>
                        <artifactId>dockerfile-maven-plugin</artifactId>
                        <configuration>
                            <skipDockerInfo>true</skipDockerInfo>
                            <dockerfile>docker/Dockerfile-develop</dockerfile>
                            <repository>private:18445/application</repository>
                            <tag>DEV-${project.version}</tag>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

## What do you expect

maven to build two images with:

mvn -f pom.xml package -B -am -P docker-production,docker-develop -Dmaven.source.skip=true -DskipTests=true

....
[INFO] Detected build of image with id 6cec96b1f11c
[INFO] Successfully built private:18445/application:PROD-2.1.0-SNAPSHOT
....
[INFO] Detected build of image with id 6cec96b1f115
[INFO] Successfully built private:18445/application:DEV-2.1.0-SNAPSHOT
...

## What happened instead

only one image is build, the profile thats places the last one in pom.xml

...
[INFO] Detected build of image with id 6cec96b1f11c
[INFO] Successfully built private:18445/application:DEV-2.1.0-SNAPSHOT

## Software:

- Spotify's dockerfile-maven version: 1.4.10

**Comment by mattnworb** [comment]
I could be wrong, but I think that the configuration from multiple profiles are simply merged together when the plugin executes - which seems to match the output you see when the plugin builds just one image.

Have you tried specifying multiple `<execution>` elements for the plugin, with a different `<id>` for each profile? I believe that multiple executions is how you get a plugin to execute more than once.

**Comment by KristijanL** [comment]
oh 😅  its working with multiple `<execution>` elements and diffrent configuration per it! thanks!
