### ISSUE TITLE
build time takes too long after update  version 1.4.10 to 1.4.13

### ISSUE THREAD

**Issue by ibrahimkarayel** [spotify/dockerfile-maven#329]
## Description

build time takes too long after update  version 1.4.10 to 1.4.13

## How to reproduce

update version as 1.4.13

## What do you expect

on my machine the build with 1.4.10 takes near to 35.645 s and  build with 1.4.13 takes   01:39 min 

## What happened instead

build time 4 times longer than before

## Software:

- docker version: 

Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false

- docker-maven-plugin version: 1.4.13
- maven version: 
pache-maven-3.6.0
Java version: 11.0.1, vendor: Oracle Corporation, runtime:  Java\jdk-11.0.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

## Full backtrace
https://github.com/ibrahimkarayel/message-post
clone project update 

>  <spotify.docker.version>1.4.10</spotify.docker.version>

build project with : ``` mvn clean install -Pdocker```
```text
[build with version: 1.4.13 
[INFO] Total time:  01:39 min
[INFO] Finished at: 2019-10-19T11:23:56+02:00


build with version:: 1.4.10
[INFO] Total time:  35.645 s
[INFO] Finished at: 2019-10-19T11:18:42+02:00]
```

**Comment by shoyu666** [comment]
+1

**Comment by dousp** [comment]
+1
when the console print "[INFO] Image will be built as xxxxx/xxx"
It wastes too much time to step build

**Comment by mcekovic** [comment]
+1, seems that the plugin is doing something that takes ~1 minute before actually starting a Docker image build. I tried debugging with -X -e, and nothing is printed to console during this ~1 minute.
Last output printed before this ~1m pause is:

[INFO] Image will be built as strangeforest/hello-docker:spotify
[INFO] 
[DEBUG] Executing "docker-credential-desktop get"

During this one minute, on my machine with 8 logical cores, 4 cores go to 100% utilization, 2 in process com.docker.proxy.exe and 2 in Maven JVM.
Tried on 2 different machines with Windows 10 (work and home) and behavior is identical.
The regression has been introduced in 1.4.11.

This makes the plugin fully unusable, it provides just slowdown and no benefits over simple Docker client execution via Maven exec plugin.

**Comment by mattnworb** [comment]
@mcekovic thanks for mentioning the log messages you see, that sounds like a good clue.

Do you see a similar pause if you run `echo strangeforest | docker-credential-desktop get` at the command line?

You can also run it like `time (echo strangeforest | docker-credential-desktop get)` to measure the time it takes for the command to run and return.

**Comment by mcekovic** [comment]
echo strangeforest | docker-credential-desktop get
credentials not found in native keychain

You probably meant I should execute:
echo https://index.docker.io/v1/ | docker-credential-desktop get
{"ServerURL":"https://index.docker.io/v1/","Username":"mcekovic","Secret":"***"}

The command exits immediately. I tried using image name mcekovic/hello-docker (with my DockerHub username) and behavior of Spotify plugin is the same:

[INFO] Image will be built as mcekovic/hello-docker:spotify
[INFO] 
[DEBUG] Executing "docker-credential-desktop get"

Pause of 1 minute is still there and during the pause 4 CPU cores are at 100% (my Docker Desktop Engine is configured with default 2 cores)

**Comment by DRoppelt** [comment]
I came here from https://github.com/spotify/dockerfile-maven/issues/337

This is still an issue with 1.4.13
Downgrade to 1.4.10 + exposing localhost:2735 serves as a workaround.

On my machine, the call
``` 
C:\Users\ddroppelt>echo https://index.docker.io/v1/ | docker-credential-wincred get
credentials not found in native keychain
```

Resolves immeadiatly.

**Comment by jeterson** [comment]
Same problem here, sometimes it take 4 minutos for complete build.

**Comment by ronjonsilver** [comment]
+1

**Comment by robgratz** [comment]
+1

**Comment by ajoshi83** [comment]
Yes, the issue still exists for 1.4.13.  Take around 5 mins to build an image even the base image does exist on the box.

**Comment by kamranghiasvand** [comment]
Same problem
Executing "docker-credential-desktop get" takes too time
version 1.4.13

**Comment by romalev** [comment]
I am hoping this is gonna get addressed in `1.4.14` release ;)

**Comment by maciekgaszynski** [comment]
I'm facing the same issue and tried to debug the plugin during the maven build. I got to the point where the build process hangs on writing to the output stream at:
`com/spotify/docker-client/8.16.0/docker-client-8.16.0-shaded.jar!/com/spotify/docker/client/shaded/org/glassfish/jersey/message/internal/ReaderWriter.class:53`
when sending an `application/tar` request to the `npipe://localhost:80/build...` endpoint. 

This lasts for like 20-30 seconds for a really small docker build context and then the build proceeds. 

Hopefully, this will be useful for someone familiar with this plugin internals.

**Comment by petrucristescu** [comment]
I have the same issue. With 1.4.10 it works fine but not with 1.4.13.

**Comment by petrucristescu** [comment]
Any news with this one?

**Comment by DRoppelt** [comment]
Usually I would not go around and promote a different project in a ticket, but since this is the official stance according to the `README.md` and nothing is happening here:

> At this point, we're not developing or accepting new features or even fixing non-critical bugs.

I had followed the issue too, but meanwhile switched to a maven-plugin that still has active development and works similarily (at least for my usecase): "docker-maven-plugin" by frabic8 (https://dmp.fabric8.io)

```
<properties>
  <!-- fabric8 docker-maven-plugin config : https://dmp.fabric8.io  -->
  <docker.push.registry>your.custom.registry.io</docker.push.registry>
  <docker.verbose>true</docker.verbose><!-- make progress during build visible, sample:"INFO] DOCKER> Step 4/6 : ADD target/${JAR_FILE} /app/app.jar"-->
</properties>

<plugin>
  <groupId>io.fabric8</groupId>
  <artifactId>docker-maven-plugin</artifactId>
  <version>0.38.1</version>
  <configuration>
    <sourceDirectory>${project.basedir}</sourceDirectory>
    <images>
      <image>
        <name>%g/%a:%v</name><!-- default is "%g/%a:%l", g: last element of grouIp, a: artifactId, l: project.version, unless -SNAPSHOT then it is latest. v (unlinke l) has no fallback to latest if *-SNAPSHOT -->
        <build>
          <dockerFile>Dockerfile</dockerFile>
          <args>
            <JAR_FILE>${project.build.finalName}.jar</JAR_FILE>
          </args>
          <!-- when doing multiple snapshot-builds, the cache wont register changes to the contents of a JAR.
          So the jar changes, but the image may be rebuild from cache with the older jar -> snapshot builds are not predictable with cache -->
          <noCache>true</noCache>
        </build>
      </image>
    </images>
  </configuration>
</plugin>
```

`mvn docker:build`  builds the image and `mvn docker:push` pushes it. Here the plugin is not bound to a lifecycle and explicitly called after a `mvn package`

The plugin can do a bunch of other stuff, but this here replaced what I used the spotify one for

**Comment by maksymgendin** [comment]
Since we already started to evaluate alternatives, I would also suggest here https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin. I used it in my projects and it worked very well.

**Comment by DRoppelt** [comment]
One thing to keep in mind with jib: it is dockerfile-less (and no daemon too) and therefore might not be a 1:1 migration (or just not possible) if anything more fancy than "copy my jar into the image" happens. Things such as "apk add <some lib>" or "add following custom CA to my cacerts" do not work in jib.
