### ISSUE TITLE
how to overwrite an existing Docker image ?

### ISSUE THREAD

**Issue by magicnana999** [spotify/dockerfile-maven#335]
dockerfile-maven-plugin 1.4.6
maven version: 3.3.9

![image](https://user-images.githubusercontent.com/45278519/70421318-91206700-1aa4-11ea-90b1-553864dc7ccc.png)

**Comment by felixklauke** [comment]
You can override an image by pushing an image with the same tag again. But that shouldn't be a problem with this project, or am I getting something wrong?
