### ISSUE TITLE
Should dockerfile be child of the `contextDirectory`?

### ISSUE THREAD

**Issue by jcchavezs** [spotify/dockerfile-maven#336]
**FEATURE REQUEST**:

## Description

Relax the condition where `dockerfile` should be a child element of `contextDirectory`: https://github.com/spotify/dockerfile-maven/blob/15780af5df74e337fa4f67d564585b1ad7a9b47e/plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java#L282. This is not an ideal restriction as for example `docker-compose` allows to have something like:

```yaml
  myapp:
    build:
      context: ./path
      dockerfile: ../Dockerfile
```

## How to reproduce

```xml
<plugin>
                    <groupId>com.spotify</groupId>
                    <artifactId>dockerfile-maven-plugin</artifactId>
                    <version>1.4.13</version>
                    <executions>
                        <execution>
                            <id>default-cli</id>
                            <goals>
                                <goal>build</goal>
                                <goal>push</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <repository>${dockerfile.registryUrl}/library/${project.artifactId}</repository>
                        <tag>${git.commit.id}</tag>
                        <contextDirectory>${project.parent.basedir}/${project.name}</contextDirectory>
                        <dockerfile>${project.parent.basedir}/Dockerfile</dockerfile>
                        <buildArgs>
                            <APP_NAME>${project.name}</APP_NAME>
                        </buildArgs>
                        <useMavenSettingsForAuth>true</useMavenSettingsForAuth>
                        <googleContainerRegistryEnabled>false</googleContainerRegistryEnabled>
                        <noCache>true</noCache>
                    </configuration>
                </plugin>
```

## What do you expect

Accept any location for dockerfile

## What happened instead

Shows an error if it is not a child file

I can come up with a PR for this.

**Comment by Tychom** [comment]
Not only is this possible in docker-compose but also with docker build:

`docker build -f ../Dockerfile ./path`

So this restriction seems unnecessary.

**Comment by cr-kobyisrael** [comment]
I also think this should be supported. It's already solved in docker repo and needs to be added here as well.
see: https://github.com/docker/cli/pull/886

**Comment by jcchavezs** [comment]
Interesting how this issue is marked as stale even when no maintainers have given feedback or had a look at it.

**Comment by jcchavezs** [comment]
Does it make sense to accept issues on this repo if a bot is going to close them with no involvement from maintainers?

**Comment by stodge** [comment]
Being able to specify a path to a dockerfile makes sense to me: `<dockerfile>${project.parent.basedir}/Dockerfile</dockerfile>`. The assumption that the Dockerfile is in the context is too rigid.

But after 9 months I won't hold my breath. I'll have to look for another Maven plugin. Any suggestions?
