### ISSUE TITLE
Build takes too much time if it used together with spring-boot-maven-plugin

### ISSUE THREAD

**Issue by ProudProgrammer** [spotify/dockerfile-maven#337]
**FEATURE REQUEST:**

## Description

Build spends too much time on "Image will be built as ..." stage. More specifically according to the debug log it is Executing "docker-credential-wincred get" stage. This stage takes about 1 min.

## How to reproduce

The project is: https://github.com/ProudProgrammer/smart-lottery-service

mvn clean install -Pfast takes 8.881s
mvn clean install -Pdocker,fast takes 01:05 min
It spends too much time on Image will be built as lottery-service:1.0-SNAPSHOT stage

[INFO] --- dockerfile-maven-plugin:1.4.13:build (default) @ lottery-service-release ---
[INFO] dockerfile: null
[INFO] contextDirectory: C:\Balazs\MyRepos\smart-lottery-service
[INFO] Building Docker context C:\Balazs\MyRepos\smart-lottery-service
[INFO] Path(dockerfile): null
[INFO] Path(contextDirectory): C:\Balazs\MyRepos\smart-lottery-service
[INFO]
[INFO] Image will be built as lottery-service:1.0-SNAPSHOT
[INFO]
[INFO] Step 1/4 : FROM openjdk:11
[INFO]
[INFO]  ---> 3a40000f62f1
[INFO] Step 2/4 : COPY release/target/lottery-service-release-1.0-SNAPSHOT.jar lottery-service.jar
[INFO]
[INFO]  ---> 2705dedc0f97
[INFO] Step 3/4 : EXPOSE 8081
[INFO]
[INFO]  ---> Running in 2a385f827fa4
[INFO] Removing intermediate container 2a385f827fa4
[INFO]  ---> 1ca262d9992b
[INFO] Step 4/4 : ENTRYPOINT ["java","-jar","/lottery-service.jar"]
[INFO]
[INFO]  ---> Running in 001110860a50
[INFO] Removing intermediate container 001110860a50
[INFO]  ---> 20c5b2f6de9f
[INFO] Successfully built 20c5b2f6de9f
[INFO] Successfully tagged lottery-service:1.0-SNAPSHOT
[INFO]
[INFO] Detected build of image with id 20c5b2f6de9f
[INFO] Building jar: C:\Balazs\MyRepos\smart-lottery-service\release\target\lottery-service-release-1.0-SNAPSHOT-docker-info.jar
[INFO] Successfully built lottery-service:1.0-SNAPSHOT
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ lottery-service-release ---
[INFO] Installing C:\Balazs\MyRepos\smart-lottery-service\release\target\lottery-service-release-1.0-SNAPSHOT.jar to C:\Users\Balazs_Gabor\.m2\repository\org\gaborbalazs\smartplatform\lottery-service-release\1.0-SNAPSHOT\lottery-service-release-1.0-SNAPSHOT.jar
[INFO] Installing C:\Balazs\MyRepos\smart-lottery-service\release\pom.xml to C:\Users\Balazs_Gabor\.m2\repository\org\gaborbalazs\smartplatform\lottery-service-release\1.0-SNAPSHOT\lottery-service-release-1.0-SNAPSHOT.pom
[INFO] Installing C:\Balazs\MyRepos\smart-lottery-service\release\target\lottery-service-release-1.0-SNAPSHOT-docker-info.jar to C:\Users\Balazs_Gabor\.m2\repository\org\gaborbalazs\smartplatform\lottery-service-release\1.0-SNAPSHOT\lottery-service-release-1.0-SNAPSHOT-docker-info.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for lottery-service 1.0-SNAPSHOT:
[INFO]
[INFO] lottery-service .................................... SUCCESS [  0.509 s]
[INFO] lottery-service-common ............................. SUCCESS [  2.642 s]
[INFO] lottery-service-service ............................ SUCCESS [  1.127 s]
[INFO] lottery-service-web ................................ SUCCESS [  1.228 s]
[INFO] lottery-service-bet-dao ............................ SUCCESS [  0.451 s]
[INFO] lottery-service-db-dao ............................. SUCCESS [  0.402 s]
[INFO] lottery-service-application ........................ SUCCESS [  0.935 s]
[INFO] lottery-service-integration-test ................... SUCCESS [  0.433 s]
[INFO] lottery-service-release ............................ SUCCESS [ 56.734 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:05 min
[INFO] Finished at: 2020-01-09T14:51:44+01:00
[INFO] ------------------------------------------------------------------------

**In debug it can be seen that Executing "docker-credential-wincred get" causes the problem.**

[INFO] Image will be built as lottery-service:1.0-SNAPSHOT
[INFO]
[DEBUG] Executing "docker-credential-wincred get"
[INFO] Step 1/4 : FROM openjdk:11

## What do you expect

Building an image should be faster

## Software:

- `docker version`: Docker Desktop Community 2.1.0.5 (40693)
- Spotify's dockerfile-maven version: 1.4.13
- OS: Windows 10 Enterprise
- Maven: 3.6.3

## Full backtrace
build module pom.xml

```text
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>lottery-service</artifactId>
        <groupId>org.gaborbalazs.smartplatform</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>lottery-service-release</artifactId>

    <dependencies>
        <!-- Module dependencies -->
        <dependency>
            <groupId>org.gaborbalazs.smartplatform</groupId>
            <artifactId>lottery-service-application</artifactId>
        </dependency>
    </dependencies>

    <!-- Build uber-jar -->
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>org.gaborbalazs.smartplatform.lotteryservice.application.LotteryServiceApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>docker</id>
            <!-- Build docker image -->
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.spotify</groupId>
                        <artifactId>dockerfile-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <contextDirectory>${project.parent.basedir}</contextDirectory>
                            <repository>${project.parent.artifactId}</repository>
                            <tag>${project.parent.version}</tag>
                            <pullNewerImage>false</pullNewerImage>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>

parent pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<packaging>pom</packaging>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.7.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>org.gaborbalazs.smartplatform</groupId>
	<artifactId>lottery-service</artifactId>
	<version>1.0-SNAPSHOT</version>
	<name>lottery-service</name>
	<description>Lottery service for different lottery types</description>

	<properties>
		<project.version>1.0-SNAPSHOT</project.version>
		<java.version>11</java.version>

		<!-- Project versions -->
		<logging-filter.version>1.0-SNAPSHOT</logging-filter.version>

		<!-- 3rd party versions -->
		<mysql.version>8.0.17</mysql.version>
		<swagger.version>2.9.2</swagger.version>
		<junit-jupiter.version>5.5.1</junit-jupiter.version>
		<mockito-junit-jupiter.version>3.0.0</mockito-junit-jupiter.version>
		<mockito-core.version>3.0.0</mockito-core.version>
		<jayway.jsonpath.version>2.4.0</jayway.jsonpath.version>
		<docker.plugin.version>1.4.13</docker.plugin.version>
	</properties>

	<modules>
		<module>application</module>
		<module>common</module>
		<module>service</module>
		<module>db-dao</module>
		<module>bet-dao</module>
		<module>web</module>
		<module>integration-test</module>
		<module>release</module>
    </modules>

	<!-- Profiles -->
	<profiles>
		<profile>
			<id>fast</id>
			<properties>
				<maven.test.skip>true</maven.test.skip>
			</properties>
		</profile>
	</profiles>

	<!-- Available dependencies -->
	<dependencyManagement>
		<dependencies>
			<!-- Module dependencies -->
			<dependency>
				<groupId>org.gaborbalazs.smartplatform</groupId>
				<artifactId>lottery-service-application</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.gaborbalazs.smartplatform</groupId>
				<artifactId>lottery-service-web</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.gaborbalazs.smartplatform</groupId>
				<artifactId>lottery-service-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.gaborbalazs.smartplatform</groupId>
				<artifactId>lottery-service-db-dao</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.gaborbalazs.smartplatform</groupId>
				<artifactId>lottery-service-bet-dao</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.gaborbalazs.smartplatform</groupId>
				<artifactId>lottery-service-release</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.gaborbalazs.smartplatform</groupId>
				<artifactId>lottery-service-common</artifactId>
				<version>${project.version}</version>
			</dependency>

			<!-- Smart Platform dependencies -->
			<dependency>
				<groupId>org.gaborbalazs.smartplatform</groupId>
				<artifactId>logging-filter</artifactId>
				<version>${logging-filter.version}</version>
			</dependency>

			<!-- 3rd party dependencies -->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-data-jpa</artifactId>
			</dependency>
			<dependency>
				<groupId>mysql</groupId>
				<artifactId>mysql-connector-java</artifactId>
				<version>${mysql.version}</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger2</artifactId>
				<version>${swagger.version}</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger-ui</artifactId>
				<version>${swagger.version}</version>
			</dependency>
			<dependency>
				<groupId>com.jayway.jsonpath</groupId>
				<artifactId>json-path</artifactId>
				<version>${jayway.jsonpath.version}</version>
				<scope>test</scope>
			</dependency>

		</dependencies>
	</dependencyManagement>

	<!-- Common dependencies, inherited by all child modules -->
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>${junit-jupiter.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<version>${mockito-junit-jupiter.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>${mockito-core.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<!-- Available plugins -->
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>com.spotify</groupId>
					<artifactId>dockerfile-maven-plugin</artifactId>
					<version>${docker.plugin.version}</version>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
```

**Comment by mattnworb** [comment]
Do you see the same slow response if you invoke `docker-credential-wincred get` directly from the command line, like `echo ${registry_hostname} | docker-credential-wincred get` (apologies I'm not sure of the windows syntax)?

I don't think there is much that this plugin can do if your Docker config file specifies to invoke a credential helper to get credentials for certain registries and if those helper programs then are slow to respond.

**Comment by ProudProgrammer** [comment]
According to docker info, registry host is https://index.docker.io/v1/
A tried this: `echo https://index.docker.io/v1/ | docker-credential-wincred get` and I could see the answer immediately: `credentials not found in native keychain` but it always says this, the host does not matter. 

`docker info`

Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: 73EQ:S3FU:2CTZ:PRBX:KPDT:5GX4:O54C:PZIL:FZAV:N4P2:FZFK:DNCL
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 28
  Goroutines: 42
  System Time: 2020-01-09T20:01:28.2150563Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**This is my .docker/config.json**
`{"credsStore":"desktop","stackOrchestrator":"swarm"}`

**Comment by frkanm** [comment]
This seems like a duplicate to #329 . Try changing the plugin version from 1.4.13 to **1.4.10**.

**Comment by ProudProgrammer** [comment]
Thank you @frkanm, downgrade solved this problem. However, for 1.4.10 version we need to expose 2375 port without TLS.
