### ISSUE TITLE
Set the docker host to enable TLS 

### ISSUE THREAD

**Issue by prashi511** [spotify/dockerfile-maven#341]
**Is this a BUG REPORT or FEATURE REQUEST?**:

## Description

com.spotify.docker.client.shaded.org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection
 refused: connect

## How to reproduce

disable "Expose daemon on tcp://localhost:2375 without TLS" in docker
in windows.

## What do you expect
How to do push the image in docker by disabling "Expose daemon on tcp://localhost:2375 without TLS"

## What happened instead

[Describe the actual results]

## Software:

- `docker version`: [Add the output of `docker version` here, both client and server]
- Spotify's dockerfile-maven version: [Add dockerfile-maven version here]

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by feiyingmm** [comment]
How to configure ca certificate path
