### ISSUE TITLE
> > > I also encountered the same problem

### ISSUE THREAD

**Issue by wxywizard** [spotify/dockerfile-maven#345]
> > > I also encountered the same problem
> > 
> > 
> > It seems that no one has maintained it, I suggest you use jib-maven-plugin.
> 
> 谢谢，有没有demo参考下？

[官方文档](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin)，这个插件跟dockerfile-plugin不同的是，它不需要本地安装docker环境，也不需要连接远程docker环境
```yaml
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>${jib-plugin-version}</version>
                <configuration>
                    <from>
                        <image>仓库地址/镜像:版本号</image>
                        <username>xxxx</username>
                        <password>xxxx</password>
                    </from>
                    <to>
                        <image>仓库地址/镜像:版本号</image>
                        <username>xxxx</username>
                        <password>xxxx</password>
                    </to>
                    <container>
                        <jvmFlags>
                            <jvmFlag>-Dspring.profiles.active=prod</jvmFlag>
                            <jvmFlag>-Xms512m</jvmFlag>
                            <jvmFlag>-Xdebug</jvmFlag>
                        </jvmFlags>
                        <ports>
                            <port>8080</port>
                        </ports>
                    </container>
                </configuration>
                <executions>
                    <execution>
                        <id>jib-maven-plugin</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

_Originally posted by @jiangyongbing24 in https://github.com/spotify/dockerfile-maven/issues/343#issuecomment-601085964_

谢谢 但是我这么尝试他报错了
 <plugin>
            <groupId>com.google.cloud.tools</groupId>
            <artifactId>jib-maven-plugin</artifactId>
            <version>1.7.0</version>
            <configuration>
                <from>
                    <image>172.20.32.41:3272/hub.c.163.com/springcloud/java8</image>

                </from>
                <to>
                    <image>172.20.32.41:3272/sailing/${project.artifactId}:0.0.1</image>

                </to>
                <container>
                    <jvmFlags>

                        <jvmFlag>-Xms512m</jvmFlag>
                        <jvmFlag>-Xdebug</jvmFlag>
                    </jvmFlags>
                    <ports>
                        <port>7009</port>
                    </ports>
                </container>
                <allowInsecureRegistries>true</allowInsecureRegistries> 
            </configuration>
            <executions>
                <execution>
                    <id>jib-maven-plugin</id>
                    <phase>package</phase>
                    <goals>
                        <goal>build</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>

错误信息
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.7.0:build (jib-maven-plugin) on project datademo: Tried to retrieve authentication method for 172.20.32.41:3272 but failed because: registry returned error code 404; possible causes include invalid or wrong reference. Actual error output follows:
[ERROR] {"message":"page not found"}

**Comment by jiangyongbing24** [comment]
> I also encountered the same problem
> 
> It seems that no one has maintained it, I suggest you use jib-maven-plugin.
> 
> 谢谢，有没有demo参考下？
> 
> 官方文档，这个插件跟dockerfile-plugin不同的是，它不需要本地安装docker环境，也不需要连接远程docker环境
> 
>             <plugin>
>                 <groupId>com.google.cloud.tools</groupId>
>                 <artifactId>jib-maven-plugin</artifactId>
>                 <version>${jib-plugin-version}</version>
>                 <configuration>
>                     <from>
>                         <image>仓库地址/镜像:版本号</image>
>                         <username>xxxx</username>
>                         <password>xxxx</password>
>                     </from>
>                     <to>
>                         <image>仓库地址/镜像:版本号</image>
>                         <username>xxxx</username>
>                         <password>xxxx</password>
>                     </to>
>                     <container>
>                         <jvmFlags>
>                             <jvmFlag>-Dspring.profiles.active=prod</jvmFlag>
>                             <jvmFlag>-Xms512m</jvmFlag>
>                             <jvmFlag>-Xdebug</jvmFlag>
>                         </jvmFlags>
>                         <ports>
>                             <port>8080</port>
>                         </ports>
>                     </container>
>                 </configuration>
>                 <executions>
>                     <execution>
>                         <id>jib-maven-plugin</id>
>                         <phase>package</phase>
>                         <goals>
>                             <goal>build</goal>
>                         </goals>
>                     </execution>
>                 </executions>
>             </plugin>
> Originally posted by @jiangyongbing24 in #343 (comment)
> 
> 谢谢 但是我这么尝试他报错了
> 
> com.google.cloud.tools
> jib-maven-plugin
> 1.7.0
> 
> 
> 172.20.32.41:3272/hub.c.163.com/springcloud/java8
> 
>             </from>
>             <to>
>                 <image>172.20.32.41:3272/sailing/${project.artifactId}:0.0.1</image>
>             </to>
>             <container>
>                 <jvmFlags>
>                     <jvmFlag>-Xms512m</jvmFlag>
>                     <jvmFlag>-Xdebug</jvmFlag>
>                 </jvmFlags>
>                 <ports>
>                     <port>7009</port>
>                 </ports>
>             </container>
>             <allowInsecureRegistries>true</allowInsecureRegistries> 
>         </configuration>
>         <executions>
>             <execution>
>                 <id>jib-maven-plugin</id>
>                 <phase>package</phase>
>                 <goals>
>                     <goal>build</goal>
>                 </goals>
>             </execution>
>         </executions>
>     </plugin>
> 错误信息
> [ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.7.0:build (jib-maven-plugin) on project datademo: Tried to retrieve authentication method for 172.20.32.41:3272 but failed because: registry returned error code 404; possible causes include invalid or wrong reference. Actual error output follows:
> [ERROR] {"message":"page not found"}

第一：你编辑的乱七八糟的，格式都乱了，但是这样我也感觉到你from配错了
第二：404错误是什么不用我多说了吧
