### ISSUE TITLE
Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused

### ISSUE THREAD

**Issue by MelanieMonnereau** [spotify/dockerfile-maven#352]
Trying to do a mvn install and below is my full exception
Please note that i m running on windows with Linux containers AND the option "Expose daemon on tcp://localhost:2375 without TLS" is checked!

[ERROR] Failed to execute goal com.nsn.cumulocity.clients-java:microservice-package-maven-plugin:1005.7.5:package (package) on project xxxx: Execution package of goal com.nsn.cumulocity.clients-java:microservice-package-maven-plugin:1005.7.5:package failed: org.apache.maven.plugin.MojoExecutionException: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect -> [Help 1]
[

**Comment by marvinHubLook** [comment]
You can set environment variables

set DOCKER_HOST=tcp://192.168.99.100:2376
set DOCKER_MACHINE_NAME=default
set DOCKER_TLS_VERIFY=1
set DOCKER_CERT_PATH=C:\Users\panhl-a.docker\machine\machines\default
