### ISSUE TITLE
Support --no-cache

### ISSUE THREAD

**Issue by ulzha** [spotify/dockerfile-maven#4]
Hi!

I'm staring at this https://github.com/spotify/dockerfile-maven/blob/a886d80878969a902800244f752361f46989a133/plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java#L130 and I feel like I have seen this place and it had noCache or something there, but now it certainly does not.

**Comment by mattnworb** [comment]
you can set `-Ddockerfile.build.noCache` or set `<noCache>true</noCache>` in your `<configuration>`.
