### ISSUE TITLE
Support for Remove Image before build

### ISSUE THREAD

**Issue by beihaifeiwu** [spotify/dockerfile-maven#40]
like the docker-maven-plugin, provide a goal like removeImage ?

**Comment by mattnworb** [comment]
What is the use case for removing an image before building it?

**Comment by bjornbak** [comment]
I would to comment: I experience that building several times that I end up having multiple copies locally without a name and tag.

Output from docker images:

REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
debian-postgres-awscli-base   latest              947cb248393d        7 minutes ago       139MB
debian-postgres-base          latest              5f083e409665        8 minutes ago       70.2MB
<none>                        <none>              dc4889b5b1ba        About an hour ago   139MB
<none>                        <none>              fe7af7f4e275        About an hour ago   70.2MB

I expect this is @beihaifeiwu's use case. Removing the image before building would clean up the local repository.

**Comment by mattnworb** [comment]
My personal opinion is that things like cleaning up the local environment would be better left to commands like "docker system prune" etc. I don't think it is our intent to make it possible to do everything that you can do with the docker cli possible to do with a Maven goal as well. I'm not sure if other maintainers feel any different though.

**Comment by masih** [comment]
For me this about letting the build to clean after itself. Adding the image removal feature to the plugin would allow the clean up to be automated nicely, since the build knows what images it has built.

The alternative is to try and re-consturct the image names and call `docker rmi` on them, which to me doesn't sound very nice.

**Comment by kmarokas** [comment]
I have the problem building SNAPSHOT images. If the image with the same tag (e.g. 1.0.2-SNAPSHOT) is already here and running, then I get two images with the same tag. Second start of the same image uses then old one. The workaround for this is then docker rmi -f 1.0.2-SNAPSHOT. It would be nice to have this possibility in dockerfile-maven plugin configuration.

NOTE: this strange behavior with two different images tagged with same name occurs only when I am using remote docker daemon (DOCKER_HOST=tcp://...). I have done extensive tests with docker cli which behaves same.  When I am using DOCKER_HOST=unix:///var/run/docker.sock (e.g. inside container using cli docker build) then everything works fine (old Image gets untagged and the new one will be created and tagged).
