### ISSUE TITLE
 com.spotify:dockerfile-maven-plugin:1.2.2:build failed. NullPointerException

### ISSUE THREAD

**Issue by yuyu2** [spotify/dockerfile-maven#42]
Failed to execute goal com.spotify:dockerfile-maven-plugin:1.2.2:build (default-cli) on project merchant-web: Execution default-cli of goal com.spotify:dockerfile-maven-plugin:1.2.2:build failed. NullPointerException

**Comment by mattnworb** [comment]
This is fixed in the latest version, see #30
