### ISSUE TITLE
no such file or directory 

### ISSUE THREAD

**Issue by hkashlan** [spotify/dockerfile-maven#46]
Hi I have mac pc,
I have com.spotify:dockerfifle-maven-plugin:1.3.3 to build a docker container for this spring-boot app.
I am receiving:
`[INFO] Step 2/5 : ADD target/pharma-api.jar app.jar
[ERROR] ADD failed: stat /var/lib/docker/tmp/docker-builder529138473/target/pharma-api.jar: no such file or directory`

I don't know from where /var/lib/docker/tmp/docker-builder529138473/ it is coming,
and it is random

**Comment by mattnworb** [comment]
Can you share your Dockerfile? 

I would guess this is docker saying that ther eis no `target/pharma-api.jar` in the build context.

**Comment by hkashlan** [comment]
Thank you for your reply,
this is my Docker file (I don't have .dockerignore)
sorry if I can not upload my code, because I am adding this feature for existing project
`
FROM frolvlad/alpine-oraclejdk8:slim

ADD target/pharma-api.jar app.jar

RUN sh -c 'touch /app.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
`

and this the output from console

`
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building pharma-api 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.7.201606060606:prepare-agent (prepare-agent) @ pharma-api ---
[INFO] argLine set to "-javaagent:/Users/hkashlan/.m2/repository/org/jacoco/org.jacoco.agent/0.7.7.201606060606/org.jacoco.agent-0.7.7.201606060606-runtime.jar=destfile=/Users/hkashlan/Documents/mycompany/pharma project/api/target/jacoco.exec"
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:add-source (default) @ pharma-api ---
[INFO] Source directory: /Users/hkashlan/Documents/mycompany/pharma project/api/src-gen/main/java added.
[INFO] Source directory: /Users/hkashlan/Documents/mycompany/pharma project/api/target/generated-sources/java added.
[INFO] 
[INFO] --- apt-maven-plugin:1.1.3:process (default) @ pharma-api ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pharma-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 34 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ pharma-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 151 source files to /Users/hkashlan/Documents/mycompany/pharma project/api/target/classes
[WARNING] /Users/hkashlan/Documents/mycompany/pharma project/api/src/main/java/com/myapp/lib/RESTController.java: Some input files use unchecked or unsafe operations.
[WARNING] /Users/hkashlan/Documents/mycompany/pharma project/api/src/main/java/com/myapp/lib/RESTController.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ pharma-api ---
[INFO] Not copying test resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ pharma-api ---
[INFO] Not compiling test sources
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ pharma-api ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:unpack-dependencies (default) @ pharma-api ---
[INFO] newrelic-agent-3.32.0.jar already exists in destination.
[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ pharma-api ---
[INFO] Building jar: /Users/hkashlan/Documents/mycompany/pharma project/api/target/pharma-api-0.1.0.jar
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.1.RELEASE:repackage (default) @ pharma-api ---
[INFO] 
[INFO] --- dockerfile-maven-plugin:1.3.0:build (default) @ pharma-api ---
[INFO] Building Docker context /Users/hkashlan/Documents/mycompany/pharma project/api
[INFO] 
[INFO] Image will be built as pharma-api:0.1.0
[INFO] 
[INFO] Step 1/5 : FROM frolvlad/alpine-oraclejdk8:slim
[INFO] Pulling from frolvlad/alpine-oraclejdk8
[INFO] Digest: sha256:6d746c651b382696a827beacf0eb416f6e67812fc8132da6964fa562824520ad
[INFO] Status: Image is up to date for frolvlad/alpine-oraclejdk8:slim
[INFO]  ---> c887553bc35c
[INFO] Step 2/5 : ADD target/pharma-api.jar app.jar
[ERROR] ADD failed: stat /var/lib/docker/tmp/docker-builder557173559/target/pharma-api.jar: no such file or directory
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not build image
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:164)
	at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:95)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:219)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:208)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.spotify.docker.client.exceptions.DockerException: ADD failed: stat /var/lib/docker/tmp/docker-builder557173559/target/pharma-api.jar: no such file or directory
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:105)
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:63)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1389)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1348)
	at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:157)
	... 25 more
[INFO] Building Docker context /Users/hkashlan/Documents/mycompany/pharma project/api
[INFO] 
[INFO] Image will be built as pharma-api:0.1.0
[INFO] 
[INFO] Step 1/5 : FROM frolvlad/alpine-oraclejdk8:slim
[INFO] Pulling from frolvlad/alpine-oraclejdk8
[INFO] Digest: sha256:6d746c651b382696a827beacf0eb416f6e67812fc8132da6964fa562824520ad
[INFO] Status: Image is up to date for frolvlad/alpine-oraclejdk8:slim
[INFO]  ---> c887553bc35c
[INFO] Step 2/5 : ADD target/pharma-api.jar app.jar
[ERROR] ADD failed: stat /var/lib/docker/tmp/docker-builder864104234/target/pharma-api.jar: no such file or directory
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.710 s
[INFO] Finished at: 2017-07-14T04:59:50+02:00
[INFO] Final Memory: 65M/603M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.0:build (default) on project pharma-api: Could not build image: ADD failed: stat /var/lib/docker/tmp/docker-builder864104234/target/pharma-api.jar: no such file or directory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

`
my pom file

`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.myapp</groupId>
    <artifactId>pharma-api</artifactId>
    <version>0.1.0</version>
    <packaging>jar</packaging>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.1.RELEASE</version>
        <relativePath/>
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
        <start-class>com.myapp.Application</start-class>
        <querydsl.version>4.1.4</querydsl.version>
        <spock.version>1.1-groovy-2.4-rc-2</spock.version>
        <swagger2.version>2.6.0</swagger2.version>
        <dockerfile.version>1.3.0</dockerfile.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>0.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.bgee.log4jdbc-log4j2</groupId>
            <artifactId>log4jdbc-log4j2-jdbc4.1</artifactId>
            <version>1.16</version>
        </dependency>
         <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-jpa</artifactId>
            <version>${querydsl.version}</version>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-sql-spring</artifactId>
            <version>${querydsl.version}</version>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-apt</artifactId>
            <version>${querydsl.version}</version>
        </dependency>


<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-log4j12</artifactId>
  <version>1.6.1</version>
</dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.16.10</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.newrelic.agent.java</groupId>
            <artifactId>newrelic-agent</artifactId>
            <version>3.32.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <scope>runtime</scope>
            <version>1.5.4</version>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
   <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>5.1.6</version>
    </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>${swagger2.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>${swagger2.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.7</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.spockframework</groupId>
            <artifactId>spock-core</artifactId>
            <version>${spock.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.spockframework</groupId>
            <artifactId>spock-spring</artifactId>
            <version>${spock.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
        </dependency>
        
		<dependency>
		    <groupId>commons-beanutils</groupId>
		    <artifactId>commons-beanutils</artifactId>
		    <version>1.8.3</version>
		</dependency>
		<dependency>
			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-core</artifactId>
		</dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.myapp.Application</mainClass>
                    <executable>true</executable>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src-gen/main/java</source>
                                <source>
                                    ${project.build.directory}/generated-sources/java
                                </source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
             <plugin>
                <groupId>com.mysema.maven</groupId>
                <artifactId>apt-maven-plugin</artifactId>
                <version>1.1.3</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>process</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>target/generated-sources/java
                            </outputDirectory>
                            <processor>
                                com.querydsl.apt.jpa.JPAAnnotationProcessor
                            </processor>
                        </configuration>
                    </execution>
                </executions>
            </plugin> 
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.10</version>
                <executions>
                    <execution>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeArtifactIds>newrelic-agent</includeArtifactIds>
                            <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.5</version>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Premain-Class>com.newrelic.bootstrap.BootstrapAgent</Premain-Class>
                            <Can-Redefine-Classes>true</Can-Redefine-Classes>
                            <Can-Retransform-Classes>true</Can-Retransform-Classes>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.eluder.coveralls</groupId>
                <artifactId>coveralls-maven-plugin</artifactId>
                <version>4.3.0</version>
                <configuration>
                    
                    <repoToken>${env.COVERALLS_TOKEN}</repoToken>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.7.7.201606060606</version>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
			
			<plugin>
			  <groupId>com.spotify</groupId>
			  <artifactId>dockerfile-maven-plugin</artifactId>
			  <version>${dockerfile.version}</version>
			  <executions>
			    <execution>
			      <id>default</id>
			      <goals>
			        <goal>build</goal>
			        <goal>push</goal>
			      </goals>
			    </execution>
			  </executions>
			  <configuration>
			  	<repository>pharma-api</repository>
			    <tag>${project.version}</tag>
			    <outputDirectory>docker</outputDirectory>
			    <verbose>true</verbose>
			  </configuration>
			</plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spring-releases</id>
            <url>https://repo.spring.io/libs-release</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-releases</id>
            <url>https://repo.spring.io/libs-release</url>
        </pluginRepository>
    </pluginRepositories>

</project>

`

**Comment by mattnworb** [comment]
Looks like your build is producing `target/pharma-api-0.1.0.jar` ...

```
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ pharma-api ---
[INFO] Building jar: /Users/hkashlan/Documents/mycompany/pharma project/api/target/pharma-api-0.1.0.jar
```

... and by the time the dockerfile plugin runs, no file named `target/pharma-api.jar` exists:

```
[INFO] --- spring-boot-maven-plugin:1.4.1.RELEASE:repackage (default) @ pharma-api ---
[INFO] 
[INFO] --- dockerfile-maven-plugin:1.3.0:build (default) @ pharma-api ---
[INFO] Building Docker context /Users/hkashlan/Documents/mycompany/pharma project/api
[INFO] 
[INFO] Image will be built as pharma-api:0.1.0
[INFO] 
[INFO] Step 1/5 : FROM frolvlad/alpine-oraclejdk8:slim
[INFO] Pulling from frolvlad/alpine-oraclejdk8
[INFO] Digest: sha256:6d746c651b382696a827beacf0eb416f6e67812fc8132da6964fa562824520ad
[INFO] Status: Image is up to date for frolvlad/alpine-oraclejdk8:slim
[INFO]  ---> c887553bc35c
[INFO] Step 2/5 : ADD target/pharma-api.jar app.jar
[ERROR] ADD failed: stat /var/lib/docker/tmp/docker-builder557173559/target/pharma-api.jar: no such file or directory
```

I'm not sure what file name you intend the jar produced by your build to have but the output seems to indicate this doesn't really have anything to do with this plugin but rather the configuration you have for the jar name (and whether or not `spring-boot-maven-plugin:1.4.1.RELEASE:repackage` should be doing anything when it runs, it seems to have no output).
