### ISSUE TITLE
how to include another resources

### ISSUE THREAD

**Issue by ghost** [spotify/dockerfile-maven#50]
i want to add project war file ,but this plugin seem not support resources configuration.

**Comment by davidxia** [comment]
Are you trying to add the war file into your docker image? If so, see the
example Dockerfile here https://github.com/spotify/dockerfile-maven/#example
.

**Comment by davidxia** [comment]
Is this still an issue? If not, I'll close.

**Comment by davidxia** [comment]
Hm, that user has been deleted...
