### ISSUE TITLE
NullPointer on mvn package

### ISSUE THREAD

**Issue by jpwijbenga** [spotify/dockerfile-maven#53]
When using Eclipse and Maven on Windows 10 with Docker for Windows 17.06, dockerfile plugin 1.3.0 reports a null pointer exception. Any ideas? Or need more info?
[stack.txt](https://github.com/spotify/dockerfile-maven/files/1176834/stack.txt)

**Comment by mattnworb** [comment]
see #30, this is fixed in 1.3.2, although the latest version is 1.3.4 now

**Comment by jpwijbenga** [comment]
Thanks!
