### ISSUE TITLE
Substitute build final name in Dockerfile

### ISSUE THREAD

**Issue by ffazil** [spotify/dockerfile-maven#56]
How do I replace the artifact final name in the Dockerfile instead of hardcoding it? Something like `ADD target/@build.finalName@ app.jar` .

**Comment by seanson** [comment]
Variables can only be passed to Dockerfiles as buildArgs. These must be first defined in your pom.xml's configuration for the plugin:
```                 
                    <configuration>
                      <buildArgs>
                        <ARTIFACT_FINALNAME>${project.build.finalName}</ARTIFACT_FINALNAME>
                      </buildArgs>
                    </configuration>
                  </plugin>```

And then defined in your Dockerfile as an ARG:
```
ARG ARTIFACT_FINALNAME

COPY target/${ARTIFACT_FINALNAME}.jar /usr/share/gtau/service.jar
```

**Comment by ffazil** [comment]
Thanks, will try and update.
