### ISSUE TITLE
shouldn't the name of the artifact-id be dockerfile-maven

### ISSUE THREAD

**Issue by pprazzi** [spotify/dockerfile-maven#57]
Now in the documentation it states 

`<artifactId>dockerfile-maven-plugin</artifactId>`

Shouldn't we refer to 

`<artifactId>dockerfile-maven</artifactId>`

If so, why are there no 'jars' at [https://repo1.maven.org/maven2/com/spotify/dockerfile-maven/](https://repo1.maven.org/maven2/com/spotify/dockerfile-maven/)

**Comment by mattnworb** [comment]
No: https://repo1.maven.org/maven2/com/spotify/dockerfile-maven-plugin/1.3.4/

The github repo has multiple Maven modules: https://github.com/spotify/dockerfile-maven/blob/master/plugin/pom.xml
