### ISSUE TITLE
Allow docker authentication from maven settings

### ISSUE THREAD

**Issue by rlodge** [spotify/dockerfile-maven#64]
It would be convenient to allow docker authentication using the regular server configuration in the maven settings.xml file.  This would make the builds more portable, allow easier setup on build servers etc. which already have these settings configured, and would also avoid conflicts with changes in the docker configuration (my mac's docker daemon keeps _removing_ my auth settings and storing them in "osxkeychain", so every day I have to re-add the settings correctly.
I propose adding a new property to the configuration:

```xml
<useMavenSettingsForAuth>true</useMavenSettingsForAuth>
```

Which will add a new provider for the authorization.

**Comment by davidxia** [comment]
Closed by https://github.com/spotify/dockerfile-maven/pull/65
