### ISSUE TITLE
Question: mvn package without building the Docker image

### ISSUE THREAD

**Issue by blueelephants** [spotify/dockerfile-maven#67]
I would like to use a two step approach (as the old plugin worked):
(1) `mvn package` to only build my jar file without building the Docker image
(2) `mvn dockerfile:build` to build my Docker Image

Is there a way to modify the plugin (overwrite via pom.xml settings) that I can achieve this?

Thanks for any help.

**Comment by alphaho** [comment]
If you are following the example from `README.md`, like below:
```
<plugin>
  <groupId>com.spotify</groupId>
  <artifactId>dockerfile-maven-plugin</artifactId>
  <version>${version}</version>
  <executions>
    <execution>
      <id>default</id>
      <goals>
        <goal>build</goal>
        <goal>push</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <repository>spotify/foobar</repository>
    <tag>${project.version}</tag>
  </configuration>
</plugin>
```

I think you can achieve it through dropping the whole `<executions>...</executions>` or maybe just `<goal>build</goal>` from the snippet, which has bound `dockerfile:build` into the `package` phase.

**Comment by mattnworb** [comment]
I think the above point is right, all you should need to do is not bind any executions of the plugin in your Pom.

**Comment by blueelephants** [comment]
Thanks a lot @alphaho and @mattnworb  - This solution works.
