### ISSUE TITLE
Dockerhub private organization repo - no pull access

### ISSUE THREAD

**Issue by oliver-whiteman** [spotify/dockerfile-maven#68]
I'm having issues pulling images from a private dockerhub organization repo using the plugin

Pulling the image using docker pull works fine:

docker pull company/base-image:0.0.1

But running mvn install I get:

[ERROR] repository company/base-image not found: does not exist or no pull access

Any suggestions?

**Comment by mattnworb** [comment]
Have you seen [the part of the readme that explains the auth support?](https://github.com/spotify/dockerfile-maven#authentication-and-private-docker-registry-support)

what does your docker config file look like?

**Comment by oliver-whiteman** [comment]
Yeah saw that but not certain how it works tbh and why it would differ from running command line - I was assuming that this also uses the config.json

{
        "auths": {
                "https://index.docker.io/v1/": {}
        },
        "credsStore": "osxkeychain"
}

**Comment by mattnworb** [comment]
See https://github.com/spotify/dockerfile-maven/issues/24

**Comment by mattnworb** [comment]
I'm going to close this since the root issue is in #24. There are some workarounds mentioned in that issue until we have credsstore support.
