### ISSUE TITLE
"Manifest not found" when using a local base

### ISSUE THREAD

**Issue by aayars** [spotify/dockerfile-maven#70]
I have a project using a base image (via FROM line) which is only available locally. `docker build` works fine when invoked directly.

When building with Maven, the build fails with "Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.5:build (default) on project {{ my project }}: Could not build image: manifest for {{ my project }} not found -> [Help 1]"

It seems dockerfile-maven is reaching out to the public registry, rather than using the locally available image. Is there a way to force the java client to use local images?

**Comment by aayars** [comment]
Nevermind, found this closed PR: https://github.com/spotify/dockerfile-maven/issues/55

**Comment by bhatnagarm** [comment]
I found this issue still relevant for version 1.4.4
