### ISSUE TITLE
Invalid RSA private key when using Docker client with maven dockerfile:build with Docker Data Center 17.06

### ISSUE THREAD

**Issue by blueelephants** [spotify/dockerfile-maven#74]
Hello,

I am experiencing an "Invalid RSA Private Key" exception, coming from Spotify's underlying Docker Client when running `mvn dockerfile:build` against a remote Docker Data Center Cluster 17.06.

I have therefore opened an issue within the Docker client repo [here](https://github.com/spotify/docker-client/issues/887) as I think this location is more appropriate.

I would welcome if any people looking at this issue-tracker could also give me some help.

Many thanks.

**Comment by grumpymatt** [comment]
Looks like this is an issue in the docker client see:
https://github.com/spotify/docker-client/pull/1033

**Comment by chrsoo** [comment]
This issue is resolved by commit 424cba1 and can be closed.
