### ISSUE TITLE
Release for version 1.3.6

### ISSUE THREAD

**Issue by IrimieBogdan** [spotify/dockerfile-maven#76]
Will there be a  1.3.6 release? The README states `Since version 1.3.6, you can authenticate using your maven settings.xml instead of docker configuration. Just add configuration similar to:`, but there is no release with this version yet.

**Comment by mattnworb** [comment]
Hey, I've just now released v1.3.6, it might take some time for the artifacts to be available in Maven Central.

**Comment by IrimieBogdan** [comment]
Thank you!

**Comment by IrimieBogdan** [comment]
Hi @mattnworb, wold it be possible to offer some time estimation for availability of release 1.3.6 on Maven Central?

**Comment by davidxia** [comment]
@IrimieBogdan It's already there http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.spotify%22%20AND%20a%3A%22dockerfile-maven%22
