### ISSUE TITLE
Maven Settings encryption support

### ISSUE THREAD

**Issue by zebu** [spotify/dockerfile-maven#78]
Please add support for encrypted passwords in maven settings.xml. This was supported in docker-maven but appear to not have been implemented in dockerfile-maven.

attached patch adding functionality

[dockerfile-maven.txt](https://github.com/spotify/dockerfile-maven/files/1325902/dockerfile-maven.txt)

**Comment by mycrEEpy** [comment]
+1 would like to see this soon

**Comment by davidxia** [comment]
added in https://github.com/spotify/dockerfile-maven/pull/167
