### ISSUE TITLE
Avoid generating *-docker-info.jar

### ISSUE THREAD

**Issue by destebanm** [spotify/dockerfile-maven#83]
Hey guys!

Is there any way to avoid generating the -docker-info.jar?

If not, how can I change its name?

Thanks!

**Comment by vromero** [comment]
I'm having problems with an old nexus and the -info. I'd love to be able to skip its creation/deploy.

**Comment by sschnabe** [comment]
This should be fixed with commit with [pr259](https://github.com/spotify/dockerfile-maven/pull/259) ?

**Comment by dcfsc** [comment]
v1.4.10 includes [PR259 ](https://github.com/spotify/dockerfile-maven/pull/259) and accepts
```
<configuration>
   <skipDockerInfo>true</skipDockerInfo>
</configuration>
```
Thank goodness, since I was having an issue running `dockerfile-maven` using a jgitflow release plugin due to duplicate writes of the docker info jar to a release Maven repo == failure!

**Comment by mattnworb** [comment]
@angelosanramon see the comment above yours, this was added in #259
