### ISSUE TITLE
Maven Authentication with encrypted password fails

### ISSUE THREAD

**Issue by gokgozf** [spotify/dockerfile-maven#84]
After using mvn -ep to encrypt the pass like following 
```
<server>
      <id>repo:8080</id> 
      <username>gokgozf</username> 
      <password>{hereisthehash}</password>              
</server>
```

Plugin authentication failes.
MavenRegistryAuthSupplier class reads the password as plain text [L72](https://github.com/spotify/dockerfile-maven/blob/master/plugin/src/main/java/com/spotify/plugin/dockerfile/MavenRegistryAuthSupplier.java#L72). Also mentioned in [link](http://maven.40175.n5.nabble.com/Decrypting-server-password-td2795412.html)

**Comment by zebu** [comment]
See my issue on this. There is no support in the code for maven encrypted passwords. I provided a patch to add it. https://github.com/spotify/dockerfile-maven/issues/78

**Comment by davidxia** [comment]
added in #167
