### ISSUE TITLE
Custom Dockerfile name

### ISSUE THREAD

**Issue by lodrantl** [spotify/dockerfile-maven#85]
We are using the same maven project to build both Linux and Windows images with two Dockerfiles. One named Dockerfile and one Dockerfile.windows.

It would be very useful if the plugin had this configuration option.

Does Spotify docker client support this?

**Comment by jguady** [comment]
If this could also be implemented to specify the docker file path as well. I use a .docker folder to house multiple docker files.

**Comment by npiguet** [comment]
Solved by pull request #89

**Comment by lodrantl** [comment]
@npiguet Thanks
