### ISSUE TITLE
Could not find a docker config. Please run 'docker login' to create one

### ISSUE THREAD

**Issue by dulimitta** [spotify/dockerfile-maven#92]
I am using dockerfile-maven to push spring boot micro service to AWS ECS. I am getting the below error.
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.11:build (docker-build) on project sample-service: 
Exception caught: Could not find a docker config. Please run 'docker login' to create one -> [Help 1] 

I already installed aws cli and completed "aws ecr get-login --no-include-email --region us-east-1" setup. I could see the token added on docker config.

Please suggest.

**Comment by davidxia** [comment]
Can you provide more info on the structure of your docker config file (and path) and your dockerfile-maven configuration?

**Comment by dulimitta** [comment]
Closing this issue as the error has been resolved.

**Comment by suraj0057** [comment]
Any guideline to resolve, I am facing same error with ci on gitlab?
