### ISSUE TITLE
Configure by command line

### ISSUE THREAD

**Issue by alejandropg** [spotify/dockerfile-maven#93]
Hi,

I'm in a Jenkins pipeline and I'm trying to overwrite some options (for example the `tag`) by command line, but I can't.

I tried:
```
sh 'mvn dockerfile:push -Dtag=aaa -Ddockerfile.tag=bbb -Dpush.dockerfile.tag=ccc'
```
but nothing works.

I suppose that I can define a maven property in the pom, like: `<tag>${myTag}</tag>` and do `mvn dockerfile:push -DmyTag=aaa` but I would like to know if there is a more direct and simple way.

Thanks a lot!

**Comment by mattnworb** [comment]
You can specify the tag property [with `-Ddockerfile.tag` to `dockerfile:push`](https://github.com/spotify/dockerfile-maven/blob/master/plugin/src/main/java/com/spotify/plugin/dockerfile/PushMojo.java#L46-L50), but note that that seems to only control the name of the tag you want to push (and doesn't control the name of the tag being built, counter to what the javadoc says).

Similarly the `dockerfile:build` mojo [has a property for `-Ddockerfile.tag`](https://github.com/spotify/dockerfile-maven/blob/59c93a1b3f5af4410735c5df8ae4f27c7ed4c0af/plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java#L65-L69). 

So if you want to build and push a certain tag in the same mvn invocation, I would do:

```
$ mvn -Ddockerfile.tag=foobar ... dockerfile:build dockerfile:push
```

does that help?

**Comment by alejandropg** [comment]
A little but not really.

The problem is that if you use `-Ddockerfile.tag=foobar` this value doesn't take precedence over the configuration in pom.xml (`<configuration><tag>xxx</tag></configuration>`).

So, if you define a `<tag>` value in the pom.xml you can not overwrite it in command line with `-Ddockerfile.tag=...`

Is this the normal Maven behaviour? I thought that the command line always overwrite the pom configuration.

As a workaround I know I can define a Maven's property in the pom, like: `<tag>${myTag}</tag>` and now I can execute `mvn dockerfile:push -DmyTag=aaa`, but I would like know if there is a more direct and simple way.

Thanks!

**Comment by mattnworb** [comment]
> Is this the normal Maven behaviour?

As far as I know, yeah.

**Comment by alejandropg** [comment]
For me it does not work, at least in this case.

Please, could you try to define `<configuration><tag>xxx</ tag></ configuration>` in your `pom.xml` and check if you can override it by command line with` -Ddockerfile.tag = bar` ?

Thanks!
