### ISSUE TITLE
unix socket connexion broken since version 1.3.2 when using proxy on macos

### ISSUE THREAD

**Issue by jul1g** [spotify/dockerfile-maven#97]
hi

Not sure if it is a dockerfile-maven bug or a docker-client one.

reproduction : If i set a system proxy on macos, the plugin fail on build with the following exception

`Caused by: java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 10.X.X.X:3131 at java.net.URI.create(URI.java:852)`
(ip is masked by me)

first line from the docker client code in stack is 
'at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2440)'

After some investigations it seems that : 
before version 1.3.2 : the os detection in docker-client.DockerHost bypass the proxy configuration on unix/mac and the connection is 'DEFAULT_UNIX_ENDPOINT = "unix:///var/run/docker.sock"' : it works

after 1.3.1 : the proxy configuration is used and does not work. the DOCKER_HOST env variable is ignored . (we tried  setting DOCKER_HOST=unix:///var/run/docker.sock without succes).

Not sure if the problem is caused by the non unix socket or by the fact that proxy exceptions (like localhost) is ignored by DockerHost.

**Comment by mattnworb** [comment]
Just to be clear, can you clarify the exact properties you are setting for the system proxy and the DOCKER_HOST environment variable?

**Comment by mattnworb** [comment]
If you have the property `http.proxyHost` set, do you also have `http.nonProxyHosts` set?

**Comment by jul1g** [comment]
using the macos settings :
apple -> system pref -> network -> ethernet -> advanced -> proxys -> http and https setting + non proxy hosts 

no settings for DOCKER_HOST (but i tried using it to force unix socket : not working)

**Comment by kaqqao** [comment]
Same issue. Couldn't even guess the proxy was the cause, so this thread helped me.
As far as I know, I have not configured anything Docker-specific, e.g. the DOCKER_HOST environment variable. Just the system proxy.

**Comment by javierjeronimo** [comment]
Just created pull request #169 to update docker-client dependency to 8.11.2 to fix an issue related to nonProxyHosts property in settings.xml
