### ISSUE TITLE
problem with ADD, "no such file or directory"

### ISSUE THREAD

**Issue by kushaank** [spotify/dockerfile-maven#98]
hey, i get the following error when i try to deploy - 

```
Failed to execute goal ←[32mcom.spotify:dockerfile-maven-plugin:1.3.6:build←[m ←[1m(default)←[m on project ←[36mjson2kafka←[m: ←[1;31mCould not build image←[m: ADD failed: stat /mn
t/sda1/var/lib/docker/tmp/docker-builder180630853/target/lib: no such file or directory -> ←[1m[Help 1]←[m
```

would appreciate any help!

**Comment by mattnworb** [comment]
Hi @kushaank , without seeing your Dockerfile or having steps to reproduce it is not really possible to tell you what might be happening, but it sounds like perhaps the `target/lib` folder you might be referencing in an ADD command does not actually exist in the docker context.

**Comment by kushaank** [comment]
Yep that was it! Thank you :)

**Comment by AlessioMTX** [comment]
So how did you solve? Where did maven put the jar?
